### PR TITLE
 IRSA-2459-Cropped images are not within the selecting area

### PR DESCRIPTION
**Pull request by lznakano**
Please use the sofia cube data in the IRSA-2459.  To check what the issue is, please do the same thing in irsadev.ipac.caltech.edu.   

Test URL: https://irsawebdev9.ipac.caltech.edu/irsa-2459-Lijun/firefly/

### CODE REVIEW

**Comment by lznakano** [comment]
@Olga9999 @cgelino 
Thank you very much for testing the pull request.  Yes, you both had found out the other issue which I missed.  The other two plans (in the testing data) was failed due to exactly the same reason.  I will have a fix tomorrow.

**Comment by robyww** [comment]
@lznakano I am done, new commit is pushed.

**Comment by lznakano** [comment]
@robyww 
Thanks for fixing it there.  Yes, you are right. But I was afraid of changing the cubeCtx because it is widely used now and was worried to introduce more bugs.  I just propagated the first plane information to the other plans so that the rest plans work as well.  Since you already commit the right changes.  I will abort mine.  Thanks!

**Comment by cgelino** [comment]
Is this testable at the test URL above?

**Comment by robyww** [comment]
> Is this testable at the test URL above?

@cgelino-  @lznakano should probably do another build.

**Comment by lznakano** [comment]
I rebuilt an  URL: https://irsawebdev9.ipac.caltech.edu/firefly-Lijun-irsa-2459/firefly/


Lijun Zhang
IRSA/IPAC
Room MR206
626-395-1972

On Aug 28, 2019, at 1:14 PM, Olga9999 <notifications@github.com<mailto:notifications@github.com>> wrote:


@Olga9999 requested changes on this pull request.

I have tested the provided SOFIA cube as I was asked, the first plane cut-out was working fine, the other 2 were not aligned with their boundaries, as the first one was centered automatically, but the others were centered but were also showing the boundaries where they were cut from original image... Is it possible that I am checking not the fixed version?

**Comment by cgelino** [comment]
This looks much better.  Great job getting it fixed!  My one comment is that you can't seem to crop an image that's already been cropped.  The message just says "Crop Failed."  I have no idea if that is related to the issue being fixed here.

**Comment by Olga9999** [comment]
Thanks, guys! It works as it suppose to for the described problem with this new rebuild version.
The Elliptical selection is working by putting ellipse inside of the rectangular shaped cut-out, 
hopefully that was suppose to be done like that.
Olga

**Pull request merged**
