### PR TITLE
Dm 4485 region drawing

### PR DESCRIPTION
**Pull request by cwang2016**
region drawing for the following regions, 
circle, ellipse, box, polygon, point (circle, box, diamond, cross, x, arrow, boxcircle), line, text, annulus, box annulus, ellipse annulus.  (annulus is made for the case with at least two repeated regions of the same type). 

add the following functions to file ShapeDataObj.js
- makeRectangleByCenter, makeEllipse
- drawEllipse, 
- makeTextLocationRectangle, makeTextLocationEllipse
- update drawRectangle by adding the case which is given the rotating angle and rectangle center.

### CODE REVIEW

**Comment by robyww** [comment]
On the drawing Layer dialog: You should put the file name in the title.  When we start using the api, there might not be a file name, then you should use the drawing layer id.  If is also possible the api will provide a title. For now, put the file name in the title.

**Comment by cwang2016** [comment]
ok, the title will be updated. One more thing, when should the dialog do when the draw button is clicked? 
for now, some error message is shown below the upload button if upload or drawing fails.

**Comment by cwang2016** [comment]
And the dialog stays open for now.

**Comment by robyww** [comment]
>> One more thing, when should the dialog do when the draw button is clicked? 
Close the dialog after the upload completes successfully complete,  If it fail leave it open with a message.

**Comment by robyww** [comment]
You did a great job on this ticket! Adding more region point type support, now supporting ellipse, better annulus, and great test files. This is a big step forward in our region support. 

_I am impressed._

**Pull request merged**
