### PR TITLE
DM-15326 create LSST footprint layer

### PR DESCRIPTION
**Pull request by cwang2016**
The implementation is made to show LSST footprint layer, 
- the LSST footprint is displayed in three modes, 'fill', 'outline', 'outline with text', the text is footprint id. 
- the creation of footprint is based on the given data described by image lines at image coordinate. Data is in JSON format. 
test: 
start locally at localhost:8080/firefly/demo/ffapi-LSSTfootprint-test.html
click 'Load sample image', that will start firefly viewer with 'calexp256.fits'
click 'create footprint layer', the footprint of calexp256 will be shown on top of the image. 
(in default, the footprint is shown in 'fill' mode with outline on top of the 'fill')

### CODE REVIEW

**Comment by cwang2016** [comment]
make footprint selectable. Which the footprint is clicked around center of it, the outline color turns to be orange and the id is shown along with it.

**Comment by cwang2016** [comment]
- Trey helps fix the double draw problem for image zooming
- handle the footprint with peaks data. the peaks is shown by symbol 'x' along with footprint 'outline' or 'fill'. 
- update the default color to show the footprint in better visual effect for the sample, 'calexp256.fits'.  In order to see the footprint overlay better, you may change the color stretch of the image to be 'zscal asinh'

**Comment by robyww** [comment]
I keep getting following with the SDSS MOC:
```
Uncaught TypeError: Cannot read property 'mocGroup' of undefined
    at updateMocData (HiPSMOC.js:302)
    at HiPSMOC.js:341
```

**Comment by cwang2016** [comment]
@robyww  I don't get the same error on my side. do you do hard reload?

**Comment by robyww** [comment]
I am just going to approved this and we ca work any issues after the merge.

**Pull request merged**
