### PR TITLE
IRSA-3703_preview_image_can_be_distorted

### PR DESCRIPTION
**Pull request by deannaji**
Fix png image distortion:

Jira: https://jira.ipac.caltech.edu/browse/IRSA-3703
K8s: https://dean-irsa-3703.irsakudev.ipac.caltech.edu/applications/sofia/
Test: Search moving target "Neptune Barycenter" and click on HAWC+ then see the png's.

### CODE REVIEW

**Comment by lrebull** [comment]
dumb question: what do i click on to test this? i don't see a build to test.

**Comment by lrebull** [comment]
ah, it just showed up. :)

**Comment by deannaji** [comment]
Hehehe, sorry Luisa its my fault. I create the PR first and then I add the link after Jenkins finish the K8s build :)

**Comment by lrebull** [comment]
works!

**Review by ejoliet — APPROVED** [review]
Works!
Thank you!

**Comment by deannaji** [comment]
Thanks!! I was just about to say can you please test! :)

**Pull request merged**
