### PR TITLE
IRSA-5359: Fix Data Product Viewer not updating on changing table tabs for the 1st time

### PR DESCRIPTION
**Pull request by jaladh-singhal**
Fixes [IRSA-5359](https://jira.ipac.caltech.edu/browse/IRSA-5359)

This bug also exists in Wise, ZTF, Sofia, besides SHA

## Testing
SHA: https://irsa-5359-dataproductsviewer-fix.irsakudev.ipac.caltech.edu/applications/Spitzer/SHA

Sofia: https://irsa-5359-dataproductsviewer-fix.irsakudev.ipac.caltech.edu/applications/sofia/

Wise: https://irsa-5359-dataproductsviewer-fix.irsakudev.ipac.caltech.edu/applications/wise

ZTF: https://irsa-5359-dataproductsviewer-fix.irsakudev.ipac.caltech.edu/applications/ztf

Firefly: https://fireflydev.ipac.caltech.edu/irsa-5359-dataproductsviewer-fix/firefly

### CODE REVIEW

**Comment by wmiipac** [comment]
would it be better to separate the watcher fix from the property sheet ticket? can you do a branch from dev instead?

**Comment by wmiipac** [comment]
Tested ZTF, Sofia, SHA, all working well. Need to wait to resolve the wise regression issue which only showing one table result.

**Comment by jaladh-singhal** [comment]
> would it be better to separate the watcher fix from the property sheet ticket? can you do a branch from dev instead?

@wmiipac yes sorry, that happened by mistake. Fixed it!

**Comment by wmiipac** [comment]
Tested with fixed wise ui, works as expected.

**Review by wmiipac — APPROVED** [review]
All irsa apps tested.

**Review by robyww — APPROVED** [review]
Tested with Firefly ObsCore. Look good.

**Pull request merged**
