### PR TITLE
Dm 8252 lsst catalog image

### PR DESCRIPTION
**Pull request by lznakano**
Please test it in the following ways:

  Con and Box:  target= 9.469,-1.152,  radius = 0.01  (in degree)
  Ellipse:  semi-major-axis : 58 arcsec,  ratio: 0.62
 Polygone: pre-filled work

  1. RunDeepSource, con, box, ellipse and polygone
  2. RunDeepForcedSource: 
       AllSkey: 
           constraints:  objectId=3448068867358968
 3. Science_Ccd_Exposure
    de-select camcol and filterId, repeat the same as 1 above
 4. DeepCoadd
    de-select filterId and repeat the same as 1 above

Thanks!
Lijun

### CODE REVIEW

**Comment by cwang2016** [comment]
- push a commit for DD table handling - refresh the column selection and column constraints status when the catalog selection is changed. 
- for test on 3 & 4, the image in the tri-view doesn't reflect the searched image according to the RA&DEC columns. This was fixed by DM-8245 (merged into dev already) in which the server side feeds the ra, dec column names for different catalog cases in function 'prepareTableMeta' of LSSTCatalogSearch. Please check this again after this branch is merged.   
- Review is done. The test of all cases work well.

**Comment by ymeiymei** [comment]
I have tested the test cases Lijun provided. They all worked.

Great job!

**Comment by lznakano** [comment]
Yi & Cindy, 

Please verify the last two tables.  Without de-select camcol and filterId, they should work. 
Thanks,
Lijun

**Comment by ymeiymei** [comment]
Tried. Both tables returned all the columns.

Good job!

Thanks,

Yi

**Pull request closed without merging**
