### PR TITLE
DM-14149: HiPS depth fix, pixel readout and more cleanup of HealpixIndex

### PR DESCRIPTION
**Pull request by robyww**
Improvement to Healpix core functionallity

  - make HealpixIndex support down to level 25
  - HealpixIndex can now use all 53 bits
  - HipsUtil caching cleanup and optimization
  - significant cleanup of HealpixIndex
  - zoom down goes down to level 25
  - Hips pixel level mouse readout 
  - A little more cleanup of ServCommand.java

_to test:_

 load a hips, turn on the grid and zoom down really deep.  Notice the hips pixel level readout

### CODE REVIEW

**Comment by ejoliet** [comment]
If this changed the UI, i would ask Vandana to test it before it get merged.

**Comment by ejoliet** [comment]
The branch can be tested here: https://irsawebdev9.ipac.caltech.edu/dm-14149-hips-level-20/irsaviewer/

**Comment by robyww** [comment]
The only change in the UI is there is not real limit in the depth of zoom.  I don’t think that counts as a UI change.

**Comment by cwang2016** [comment]
Review completes. works very well. Just a question, would the HiPS image display go deeper than (N+S) if the original HiPS is order N with size (2**S x 2**S) ?

**Comment by cwang2016** [comment]
correction: 2S -> power(2, s)

**Pull request merged**
