### PR TITLE
FIREFLY-1415: Table options default size is too small

### PR DESCRIPTION
**Pull request by loitly**
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-1415

- [x] Changed popup size to 65% of viewport for table options and table info(i-icon).
- [ ] Table info: fixed layout issue; grouped collapsible panels for cleaner look.
- [ ] Replaced table cell ‘more’ (…) popup with JoyUI DropDown.  Beside it being a better solution, it also fixes the issue where the old popup appeared cropped at the edges.
- [ ] Converted column dropdown filter(down arrow button) to JoyUI Dropdown and revamp its buttons.

Test: https://fireflydev.ipac.caltech.edu/firefly-1415-tableoptions/firefly

### CODE REVIEW

**Comment by lrebull** [comment]
I'm not 100% sure what the changes are (from the user perspective) for the 2nd, 3rd, and 4th tickboxes are above - i have checked the build and it looks ok, and seems to behave ok. Some of the stuff seems to behave the same way it did on ops, which isn't entirely consistent with the wording above, so I'm just going to assume it's ok...?

**Comment by loitly** [comment]
Item 4 is the most obvious among the other 3.  No more 'x' icon; 'filter' is now replaced with a big 'Apply' button on the bottom.  'clear' link is now replaced with a small(chip) clear button on top to the checkboxes.

The flow is to do all of the selections including 'clear', then apply at the end.  Doing it interactively may pose a performance issue for BIG table.

image

**Comment by loitly** [comment]
The other 2 items, as long as it's still working properly, then that's good enough.

**Comment by robyww** [comment]
This might be outside the scope a little but I don't think the link here are Joy UI

Screenshot 2024-02-20 at 4 21 54 PM

**Review by robyww — APPROVED** [review]
Looks good. I think it looks better.

I put a separate note about TableMeta links

**Comment by lrebull** [comment]
ahhh ok. i also get the filters expanding up on my screen, not down, which kind of hindered my understanding a bit.

**Comment by loitly** [comment]
> I put a separate note about TableMeta links

No worries.  I fixed it.

**Pull request merged**
