### PR TITLE
Fixed Multiple tickets and Upload Panel improvements

### PR DESCRIPTION
**Pull request by robyww**
#### Fixed: Multiple tickets and other clean up based on discussion

 - IRSA-3249: fixed labels and clean up
 - IRSA-3930: hips color not changing when showing with images
 - IRSA-3930: bias contrast sliders are off when click up
 - IRSA-3932: color check mark and slider are not updating with color slection
 - IRSA-3938: stretch dialog out-of-sync with color table
 - Firefly-714: GREAT file crashing firefly
 - Firefly-713: table upload
 - Firefly-711: title label background
 - Firelfy-640: upload region files
 - Clean up of upload panel in case where there is only one table or image
 - Upload panel: significant clean up and error checking
 - Upload panel: single extension view
 - Upload panel: show if unsupported file without errors
 - Upload panel: support region files
 - Upload Panel: better file size feedback
 - Fixed: HiPS not centering on the entered position
 - Fixed: GREAT file no longer crashes firefly
 - File Analyzer: recognized regions files

#### Tickets
https://jira.ipac.caltech.edu/browse/IRSA-3929
https://jira.ipac.caltech.edu/browse/IRSA-3930
https://jira.ipac.caltech.edu/browse/IRSA-3932
https://jira.ipac.caltech.edu/browse/IRSA-3933
https://jira.ipac.caltech.edu/browse/IRSA-3936
https://jira.ipac.caltech.edu/browse/FIREFLY-711
https://jira.ipac.caltech.edu/browse/FIREFLY-713 - table upload feedback
https://jira.ipac.caltech.edu/browse/firefly-714 -  GREAT crashing firefly issue
https://jira.ipac.caltech.edu/browse/FIREFLY-640

#### Testing

- IRSA Viewer: https://irsa-multi-ticket.irsakudev.ipac.caltech.edu/irsaviewer/
- Firefly: https://fireflydev.ipac.caltech.edu/irsa-multi-ticket/firefly/

- Tickets: Test each ticket above
- Upload panel testing
  - Upload a region file
  - Upload an unsupported file  (try PDF, TAR, PNG)
  - load files from http://web.ipac.caltech.edu/staff/roby/data-products-test/
  - Supported files should gives errors
  - Test improved single product panel (upload single HDU fits, ipac table, single table VOTables, csv, etc)

### CODE REVIEW

**Comment by lrebull** [comment]
ooh! Cool! OK, so mixed results. Mostly listing failures than all successes with failures just for clarity. (Listing some successes just because it provides context for the failures.)

- IRSA-3929 - hint text still has period at end of only one bullet; should either have none or all should have periods.
- FIREFLY-713 (i know this wasn't tagged but some things from here fixed) - region files now acknowledge that they are regions files (yay!) but will not load (which is fine)... but there is an error that isn't spelled right. It says "no extenstion is selected" and should at the very least be "no extension is selected."  OTOH, why is the error for trying to read in a regions file that no extension is selected?  
- FIREFLY-713 - trying weird formats appropriately gives "unrecognized format" error.
- FIREFLY-713, IRSA-3929 - stuff on left hand side after reading in, before loading file, now *much* clearer!
- IRSA-3929 - file size now appropriate! "Clear" gives me the guidance back!
- IRSA-3929 - TAP ADQL query page sample queries updated!
- FIREFLY-714 (i know this wasn't tagged, but we seem to have lost some capability) - EXES still crashes tool. FIFI-LS which worked before now no longer works - I tried to load HDU 5 (wavelength table) and got "File type of HeaderOnly is not supported." GREAT more elegantly error traps now (doesn't crash), but I get "File type of HeaderOnly is not supported" when trying to load one of the image HDUs. HAWC+ dies elegantly with an error "Unable to read FITS file."
- no ticket explicitly - some of the non-SOFIA multi-HDU files you sent me yesterday don't work anymore. For the j8zs05yxq_flt.fits, even selecting one of the non-zero HDUs, I get "File type of HeaderOnly is not supported." HST file works. MIPS file doesn't - "File type of HeaderOnly is not supported." NED xml works. u40a0201m_c0f.fits works. cube-3rd* file doesn't - "File type of HeaderOnly is not supported." 
- IRSA-3932 - works! but see "also related" in the description of that ticket - I added that today, but can spring it out as a separate ticket as desired. (This latter part is still broken.)
- IRSA-3933 - seems to work much better!
- IRSA-3930 - works! (issue of color table locking to CCB still pending - can create additional ticket if desired)
- FIREFLY-711 - still a thing on this build (know it wasn't listed)
- IRSA-3844 - works, though also not listed

OK, i think that was all the loose ends I was trying to track. Seems like the apparently lost capability of loading in some multi-HDU FITS files is the largest still-pending issue.

**Comment by robyww** [comment]
region file should load, I must have broke that when I was clearning up the code.

**Comment by robyww** [comment]
@lrebull A new build is available:

- Fixed most stuff on the list
- Firefly-711 done
- region file should load
- multi HDU files should not longer give you that error.
- i still have to do more research into why the EXEC breaks firefly. It is not released to the upload panel, it is the image viewer.

**Comment by lrebull** [comment]
@robyww , Emmanuel was saying that the SOFIA files aren't standard fits, so maybe not worth a lot of time chasing them right now. Will look at new build right now.

**Comment by lrebull** [comment]
(Making this a checklist since you'd done that on my earlier comment and it seems useful. Again, mostly listing failures.)
- [ ] FIREFLY-713 - regions file now loads (yay) but message isn't grammatically correct. It says: "The region file is loaded but you will not be able to see it to you create an Image or HiPS".  It should say: "The region file is loaded but you will not be able to see it **until** you **load** an **i**mage (FITS or HiPS)." (lost word, create should be load, image should be lower case, and HiPS is an image, so say "image (FITS or HiPS)."  I think there should be a period at the end too, but it's not required.
- [ ] When you fail to select a valid HDU, it says "no extenstion is selected" and should be "no extension is selected." 
- [ ] When you select the HeaderOnly HDU, I get "no extenstion is selected" but shouldn't this be something like ""File type of HeaderOnly is not supported." like before? Because I did select an extension, it's just not a valid one.
- [ ] found a new feature I don't remember seeing before - the radio buttons for All images in one window/ One extension image per window! cool! except it doesn't seem to always appear. So that I can document it, when does that option appear?
- [ ] all the color stuff i tried, worked.

**Comment by robyww** [comment]
> found a new feature I don't remember seeing before - the radio buttons for All images in one window/ One extension image per window! cool! except it doesn't seem to always appear. So that I can document it, when does that option appear?

I did not know about it either. It turns on if you choose more then one image.

**Comment by lrebull** [comment]
Not every time, though. Just sometimes. I couldn’t figure out what triggers it.

**Comment by robyww** [comment]
it has to be image HDUs, not image and table.

**Comment by robyww** [comment]
> "File type of HeaderOnly is not supported."

@lrebull How about:
```
FITS HDU type of HeaderOnly is not supported. A Header Only HDU contains no additional data.
```

**Comment by lrebull** [comment]
sure, that's good.

**Comment by lrebull** [comment]
I can get it to show up when a mixture of images and tables and when you select all HDUs - then the radio button shows up. Most of the time, anyway.

**Comment by robyww** [comment]
Let me be more clear. It will come on only when two or more image HDUs are selected.

**Comment by robyww** [comment]
@lrebull I made a new build. I will check off the `one window per extension` thing when you confirm it is working as i described.

https://irsa-multi-ticket.irsakudev.ipac.caltech.edu/irsaviewer/

**Comment by lrebull** [comment]
- Not quite there yet. "The region file is loaded but you will not be able to see it **until to** you load an image (FITS or HiPS)" --> remove the "to" so that it is "you will not be able to see it until you load"
- "FITS HDU type of HeaderOnly is not supported. A header only HDU contains no additional data" - lost the period at the end of the second sentence. And as long as you're editing that, I didn't catch this before -- should be "A header-only HDU.." (add the hyphen).

All else ok!

**Comment by robyww** [comment]
@lrebull - new build, includes the EXECs fix.

 https://irsa-multi-ticket.irsakudev.ipac.caltech.edu/irsaviewer/

**Comment by lrebull** [comment]
ok, looks good!! i think I'm supposed to wait to update tickets until it's merged and built on irsatest, right?

**Comment by robyww** [comment]
You can update the ticket when you think best. I will merge either tonight or Monday. The I will let @ejoliet and @deannaji know to make an irsatest build .

**Comment by lrebull** [comment]
everything I'm trying seems to be working, even most of FIREFLY-718.

**Comment by lrebull** [comment]
(created FIREFLY-719 but this is likely obscure.)

**Review by ejoliet — APPROVED** [review]
I have checked that the UI improvements have been included which was the prime goal of this ticket. 
Thanks!

**Pull request merged**
