### PR TITLE
FIREFLY-805: Filter does not work on boolean type column

### PR DESCRIPTION
**Pull request by loitly**
https://jira.ipac.caltech.edu/browse/FIREFLY-805

Get exceptions when filtering boolean column:
```
Table Load Error:Invalid statement: 
"w4sigmpro.mask" IN ('true') 

```
Also  fixed a couple of minor errors showing up in the console.

Test: https://fireflydev.ipac.caltech.edu/firefly-805-boolean-col-broken/firefly/
Use attached tables in the ticket to test.

### CODE REVIEW

**Comment by gpdf** [comment]
I'll test this.  It's going to hit Data Preview 0.1 in Rubin hard - they have a lot of Boolean columns.

**Review by gpdf — APPROVED** [review]
Fixes boolean behavior.

Tested both via pull-down category-column filtering and by typing "false", "true", "=false", and "=true" into the column-head fields.

All work as expected.  Ordinary integer field filtering still works correctly, too.

Very nice!

**Comment by gpdf** [comment]
You probably still want @ejoliet to do a normal code review; I only looked at the behavior.

**Review by ejoliet — APPROVED** [review]
Works like a charm!
Thanks!

**Pull request merged**
