### PR TITLE
IRSA-642-DM-11250: fixed two bugs

### PR DESCRIPTION
**Pull request by robyww**
- fixed: IRSA-642: coverage not showing
 - fixed: DM-11250: losing color and shape changes

### CODE REVIEW

**Comment by ejoliet** [comment]
I've tested with ffapi-highlevel.html page.

Coverage is back in Firefox/Safari but not in Chrome, it seems to be broken (to me at least). Here is the console log:

`uncaught at masterSaga 
 at watchCoverage 
 TypeError: Cannot read property 'columns' of undefined
    at guessDefColumns (http://localhost:8080/firefly/firefly-dev.js:193785:35)
    at Object.getCenterColumns (http://localhost:8080/firefly/firefly-dev.js:193779:19)
    at Object.hasCoverageData (http://localhost:8080/firefly/firefly-dev.js:193743:43)
    at updateCoverage (http://localhost:8080/firefly/firefly-dev.js:193458:19)
    at watchCoverage$ (http://localhost:8080/firefly/firefly-dev.js:193379:41)
    at tryCatch (http://localhost:8080/firefly/firefly-dev.js:26274:41)
    at Generator.invoke [as _invoke] (http://localhost:8080/firefly/firefly-dev.js:26512:23)
    at Generator.prototype.(anonymous function) [as next] (http://localhost:8080/firefly/firefly-dev.js:26326:22)
    at next (http://localhost:8080/firefly/firefly-dev.js:167344:28)
    at currCb (http://localhost:8080/firefly/firefly-dev.js:167421:8)`

Then i've also tried restoring the image to default but when i do that the background becomes grey and no image comes back.

Also, when i filter a table, i can see the spinning wheel next to paging count that doesn't go away (might be a side effect of background monitor ( @loitly ?)

I couldn't  check the color and shape fix because the page i'm testing doesn't have a catalog overlay as far as i can see, has it?

**Comment by ejoliet** [comment]
I've clear my cache in Chrome and now is back! but with another error in the console you might want to check:
`uncaught at masterSaga 
 at watchCoverage 
 TypeError: Cannot read property 'color' of undefined
    at http://localhost:8080/firefly/firefly-dev.js:193628:37
    at Array.forEach (<anonymous>)
    at http://localhost:8080/firefly/firefly-dev.js:193626:21
    at watchCoverage$ (http://localhost:8080/firefly/firefly-dev.js:193422:61)
    at tryCatch (http://localhost:8080/firefly/firefly-dev.js:26274:41)
    at Generator.invoke [as _invoke] (http://localhost:8080/firefly/firefly-dev.js:26512:23)
    at Generator.prototype.(anonymous function) [as next] (http://localhost:8080/firefly/firefly-dev.js:26326:22)
    at next (http://localhost:8080/firefly/firefly-dev.js:167344:28)
    at currCb (http://localhost:8080/firefly/firefly-dev.js:167421:8)
    at takeCb (http://localhost:8080/firefly/firefly-dev.js:167492:109)`

**Comment by ejoliet** [comment]
FYI- @loitly  Spinning wheel after filtering a table was transient problem, i don't see it anymore.

**Comment by robyww** [comment]
@ejoliet I can't reproduce the first error but  I did fix the second.  Are you saying the you no longer see the first error either?

**Comment by ejoliet** [comment]
ok, i see the overlay catalog now and color and shape doesn't change after filtering or sorting but the coverage image and the overlay catalog doesn't get updated after filtering (?).

Restore feature is also good.

No error in console.

**Pull request merged**
