### PR TITLE
Firefly-853: Create dropdown to add MOC layers

### PR DESCRIPTION
**Pull request by robyww**
#### Firefly-853: Create dropdown to add MOC layers
   - Any number of MOC layers can be added
   - Preferred MOC layers are setable with a firefly option `firefly.hips.adhocMocSource`
   - MOC layers user title now instread of file name
  - added help to layers dialog
  - added support for upload
  - improved ok button on HiPS/MOC dialog
  - made the upload panel to work as a dialog
  - added test cases
  - upload panel gives better feedback when moc is recognized
  - Also fixes: Firefly-882

_tickets:_
https://jira.ipac.caltech.edu/browse/FIREFLY-853
https://jira.ipac.caltech.edu/browse/FIREFLY-882

#### Testing
 - https://fireflydev.ipac.caltech.edu/firefly-853-moc/firefly/
 - Load a Hips then click on `HiPS / MOC` dropdown
 - choose MOCS to add
 - https://fireflydev.ipac.caltech.edu/firefly-853-moc/firefly/test/test-hips-mocs.html?test=Demo+a+Setting+custom+MOC+list

### CODE REVIEW

**Review by ejoliet — CHANGES_REQUESTED** [review]
Amazing! It does what the design ticket said apart from one thing which i couldn't test. The design ticket expresses specifically that`The new Add MOC dialog should have two radio buttons at the top: "Load", "Load from URL" and "Use my MOC".` But i could only see a list of MOC, without upload of file or URL. Is it the version i'm testing?
 
BTW. Where is the list coming from? Is it easy to change per application via properties at runtime or compile time? 

Plus, i have a couple of thoughts about improvements when testing the feature:

- if more than 1 MOC is selected, we could add transparency feature (slider 0%-100%) to play with different shades
- Would it be useful to select MOC at the search form initially?
- Is the HTML API exposed the multiple MOC overlay feature, i mean, is it possible to add 3 MOCs on a HiPs map from javascript/html code, i.e. in Gator or in coverage map? 
-   I always wanted to give this feedback would it be possible to make more visual the progress status. Is very discrete spining wheel that appear in the mini toolbar. Could we make it on top of the map, or next to/change the mouse cursor? 
- Looking also to CCB/Luisa for feedback to improve the labeling and wording: 
  - Menu `HiPS/MOC` not too much telling me much, i would need to click to understand what the menu is about, in ops we had `Change HiPS` so maybe to keep it shorter -> `Edit HiPS/MOC` ?
  - Label in layers should be `MOC: <name>` for example.
  - An old request was to add a question mark anchor to the layer popup dialog (see IRSA-3498), could be done during this PR?

Apart from the help anchor, all feedback are not to necessarily to consider for now but have it for future discussions.

**Comment by ejoliet** [comment]
Another comment: the confirmation button in the pop-up dialog when adding 'MOC' says 'Search' , might be better 'Load' or 'Add' or 'Apply'?

**Comment by robyww** [comment]
> Amazing! It does what the design ticket said apart from one thing which i couldn't test. The design ticket expresses specifically thatThe new Add MOC dialog should have two radio buttons at the top: "Load", "Load from URL" and "Use my MOC". But i could only see a list of MOC, without upload of file or URL. Is it the version i'm testing?

That is why I turned the PR into a draft, after I made the PR I realized I forgot to handle the upload case and some api testing..  I am not going to do it like they asked. I want  to center on the Upload panel, so I am going to make a button to jump to the upload panel.

I have almost finished the work, I plan to update the PR in the morning.

**Comment by ejoliet** [comment]
Also not sure about the order and the name of the column in the 'Add MOC' table, scientist should weigh in on those details of the table to choose the MOC.

**Comment by robyww** [comment]
> if more than 1 MOC is selected, we could add transparency feature (slider 0%-100%) to play with different shades

The drawing layers already supports transparency. The user just has to set it.

> Would it be useful to select MOC at the search form initially?

That is probably outside the scope of the ticket.

> Is the HTML API exposed the multiple MOC overlay feature, i mean, is it possible to add 3 MOCs on a HiPs map from javascript/html code, i.e. in Gator or in coverage map?

The API has supported adding MOCs for years. Yuu can see it at `test-hips-mocs.html`, test 5

> I always wanted to give this feedback would it be possible to make more visual the progress status. Is very discrete spining wheel that appear in the mini toolbar. Could we make it on top of the map, or next to/change the mouse cursor?

I think that is also outside the scope of this PR. I just barely touched the MOC code.

> Looking also to CCB/Luisa for feedback to improve the labeling and wording:
> Menu HiPS/MOC not too much telling me much, i would need to click to understand what the menu is about, in ops we had Change HiPS so maybe to keep it shorter -> Edit HiPS/MOC ?

We can change it, but that is straight from the ticket.

> Label in layers should be MOC: <name> for example.

It is a good suggestion. I will look at doing that. It depend how hard it is to do. Like I said I barely touched the MOC drawing layer code.

?>An old request was to add a question mark anchor to the layer popup dialog (see IRSA-3498), could be done during this PR?

Yes, I will add it.

**Comment by lrebull** [comment]
I've just started this but so far my biggest complaints are things that you maybe can't do much about. (1) There is a loooooonggg time waiting of "I'm not sure it's done anything" and I'm still not sure it did anything in the end for that layer. (I seem to recall this was an issue in the last CCB meeting before the break too.) (2) We're the home of Spitzer. So I am expecting the Spitzer MOCs to be right. They're not, I don't think. I searched on a target for which *I* published the Spitzer data. The MOC says my data aren't there. Or, it just never displayed it (see item 1). I'm admittedly a bit distracted right now. I will do a more thorough job of testing this in a bit.

**Comment by robyww** [comment]
based on feedback from @ejoliet  and @cwang2016 I just did a build in which I tried to improved the working indicator some when loading a MOC. I think you will now get working feedback right away.

I can't do anything about MOC quality.

**Comment by lrebull** [comment]
FWIW, the words on the buttons and the progress indicator all look pretty good to me. I am still pretty worried about whatever weirdness is happening with the Spitzer MOCs, but the rest of it looks good.

**Review by gpdf — COMMENTED** [review]
Regarding the 

> Also fixes: [Firefly-882](https://jira.ipac.caltech.edu/browse/FIREFLY-882)

part of this PR:

I have tested it on IRSA and Gaia tap and it works as desired.  Table titles are now strings like “allwise_p3as_psd - irsa.ipac.caltech.edu” or “gaiadr2.gaia_source - gea.esac.esa.int/tap_server”, instead of uniformly "AsyncTapQuery".

We had discussed the possibility of trying to parse the table name out of the ADQL for raw-ADQL queries (as opposed to single-table UI queries for which the table name is readily known) but it appears that feature was not included in this PR.  That is OK.

**Comment by gpdf** [comment]
I don't know if we have any idea what criteria were used to determine what data were included by CDS in their creation of the IRAC[1-4] HiPS images (from which the MOCs in question were obtained), beyond this statement that one can find in the `properties` file for the IRAC1 HiPS:

> Composite map from Spitzer Legacy Programs GLIMPSE: Galactic Legacy Infrared Mid-Plane Survey Extraordinaire (Churchwell E. + Benjamin R.) C2D: From Molecular Cores to Planet-Forming Disks (Evans N.) Taurus 2: Finishing the Spitzer Map of the Taurus Molecular Clouds (Padgett D.) SAGE: Spitzer Survey of the Large Magellanic Cloud: Surveying the Agents of a Galaxy's Evolution (Meixner M.) SAGE-SMC: Surveying the Agents of Galaxy Evolution in the Tidally- Disrupted, Low-Metallicity Small Magellanic Cloud (Gordon K.) SINGS: The Spitzer Infrared Nearby Galaxies Survey - Physics of the Star-Forming ISM and Galaxy Evolution (Kennicutt R.)

Taking that at face value, it seems that only a small set of Spitzer programs were included.

**Comment by lrebull** [comment]
Oh, yeah, definitely I could tell off the top of my head (!!) that only a small set were included, but yes, I think we knew that.

**Pull request merged**
