### PR TITLE
IRSA-3498: update help anchors

### PR DESCRIPTION
**Pull request by ejoliet**
I've tried to update the help anchors id where it says 'edit' in the ticket [IRSA-3498](https://jira.ipac.caltech.edu/browse/IRSA-3498).
The build of Firefly and IRSAViewer are here for testing:

https://irsa-3498-update-helpid.irsakudev.ipac.caltech.edu/irsaviewer/

https://fireflydev.ipac.caltech.edu/irsa-3498-update-helpid/firefly/

I think that some helpId will point to IRSAViewer content but not in Firefly. Example: '#visualization.selectregion'.

Please check, and let me know. Thanks.

Upload helpid is different in IRSAViewer . this needs an IFE change, see here:https://github.com/IPAC-SW/irsa-ife/pull/158

### CODE REVIEW

**Comment by lrebull** [comment]
Wow that was fast.. but weird. visualization.selectregion exists in catalogs, discovery, finderchart, firefly, irsaviewer, and sofia. I'm confused as to why it doesn't work for you in firefly. git tells me I'm synched up to the master, for both copies of firefly docs. Any ideas?

[snorlax:app/src/toc] rebull% grep visualization.selectregion *js
catalogs_toc.js: id: 'visualization.selectregion',
discovery_toc.js: id: 'visualization.selectregion',
finderchart_toc.js: id: 'visualization.selectregion',
firefly_toc.js: id: 'visualization.selectregion',
irsaviewer_toc.js: id: 'visualization.selectregion',
irsaviewer_tocSAVEME.js: id: 'visualization.selectregion',
sofia_toc.js: id: 'visualization.selectregion',

by "irsa viewer", i mean on https://irsa-3498-update-helpid.irsakudev.ipac.caltech.edu/irsaviewer
and by "firefly", i mean on https://fireflydev.ipac.caltech.edu/irsa-3498-update-helpid/firefly
image toolbar - **works** on both irsa viewer and firefly for pointing to new spot! 
save image pop-up - **broken** on both irsa viewer and firefly - can't get the pop-up to come up! (but once it does, see "HiPS properties" below, it works)
rotate image pop-up - **broken** on both irsa viewer and firefly - can't get the pop-up to come up at all, even after HiPS properties comes up.
FITS header pop-up - **broken** on both irsa viewer and firefly - can't get the pop-up to come up. Once it does (see "HiPS properties" below), it still doesn't work. On ops, it goes to #id=visualization.fitsViewer. On irsaviewer or firefly link above, it goes to #id=visualization.tables. It should go to #id=tables. 
HiPS properties pop-up - Whoa, that window does come up, along now with some of the others I'd requested above! On ops, it goes to #id=visualization.hipsViewer. On irsaviewer or firefly link above, it goes to #id=visualization.tables. It should go to #id=tables. 
Change HiPS pop-up - works on irsaviewer but not quite on firefly; somehow it's going to the wrong place in the file. I've checked the html for firefly, and it seems right from my end, which is super weird. Oh, you just Slacked something about not grabbing the commits. I'll stop here for the moment.

**Comment by lrebull** [comment]
Given stuff happening in Slack, I'll keep going just on irsaviewer.
"catalogs"   blue tab// IRSA search - ops goes to #id=basics.catalogs - your build goes to #id=catalogs - it should go to #id=catalogs.irsacatalogs
"catalogs" blue tab// NED search - works as it should
"catalogs" blue tab// load own catalog - ops goes to #id=basics.searching - your build goes to #id=basics.searching - it should go to #id=catalogs.owncatalogs
"catalogs" blue tab// VO TAP search, lower right of window - works as it should
"catalogs" blue tab// VO SCS Search - works as it should
save   table pop-up - works as it should

**Comment by ejoliet** [comment]
> "catalogs" blue tab// load own catalog - ops goes to #id=basics.searching - your build goes to #id=basics.searching - it should go to #id=catalogs.owncatalogs

Apart from the broken ones tested above that i think they come from the out of sync repos problem we just discussed in slack, i would like to highlight out here a problem that is different with the anchor in IRSAViewer for this component 'catalogs' blue tab. 
It comes from the 'Upload' panel UI but is used in Firefly viewer somewhere else than IRSAViewer so this one might be tricky to decoupled i think.

**Comment by ejoliet** [comment]
@lrebull should i close this PR or should you review it again? Do i need to change something before you review it?

**Comment by lrebull** [comment]
I can test it again to see if the errors I got above are still there, but if this is the same code/build as before, won't it have the same errors as before?

**Comment by ejoliet** [comment]
The popups come back for me, can you double check and confirm the helpId reference updated? Thanks.

**Comment by lrebull** [comment]
OK. New Firefox private window, MacOS 10.13.6, Firefox 88.0.1. Also Chrome 90.0.4430.212.
Image toolbar new link works on both builds.
Save image pop-up doesn't ever appear for me on either the IRSA Viewer build or the firefly build, either Firefox or Chrome, so I cannot check it.
rotate image pop-up doesn't ever appear for me on either the IRSA Viewer build or the firefly build, either Firefox or Chrome, so I cannot check it.
FITS header pop-up doesn't ever appear for me on either the IRSA Viewer build or the firefly build, either Firefox or Chrome, so I cannot check it.
Do you want me to keep going? So far, just the same as before. If it doesn't work for me on any platform to which I have access, I cannot test it, even though it works for you.

**Comment by ejoliet** [comment]
You don't see the pop-up when you click on the 'save' button? Wow. I can't really say how to fix it, it works for me. The code didn't change any UI, only URL of the link.

**Comment by lrebull** [comment]
I don't know if it's the order in which I'm doing things; I'm doing the same thing I did before, copying the steps above. Here's a movie. 

https://user-images.githubusercontent.com/23038600/119420018-4f8f7600-bcb0-11eb-98b8-57a0817e10d2.mp4

**Comment by ejoliet** [comment]
Ok, i see it now in my local browser - somehow it happens on particular conditions and i see errors in the console. Probably bad version. 
Anyway, i've rebuilt and here is the version to test, hopefully it works now (same link):
IRSAViewer : 
https://irsa-3498-update-helpid.irsakudev.ipac.caltech.edu/irsaviewer/
Firefly viewer:
https://fireflydev.ipac.caltech.edu/irsa-3498-update-helpid/firefly/

Thanks!

**Comment by lrebull** [comment]
ok, it's working for me now!!
**DONE** icon far right of image toolbar points to #id=visualization.toolbar
**DONE** save image pop-up points to #id=visualization.saveimage
**DONE** rotate image pop-up points to #id=visualization.rotate
FITS header pop-up does **NOT** point to #id=tables
HiPS header pop-up does **NOT** point to #id=tables
**DONE** loaded images pop-up points to #id=visualization.loaded-images
**DONE** "change HiPS" pop-up points to #id=visualization.changehips
**PARTIALLY DONE** stats pop-up points to #id=visualization.selectregion in irsaviewer but not firefly. I can see the tag visualization.selectregion in the relevant files, so I'm not sure what I've done wrong.
"catalogs" blue tab// IRSA search does **NOT** point to #id=catalogs
**DONE** "catalogs" blue tab// NED search points to #id=catalogs.nedcatalogs
"catalogs" blue tab// load own catalog does **NOT** point to #id=catalogs.owncatalogs (DNE in firefly, surprising to me)
**DONE** "catalogs" blue tab// VO SCS Search points to #id=catalogs.voscs
**PARTIALLY DONE**save table pop-up does **NOT** point to #id=tables.save in irsaviewer, which baffles me, but it does work correctly in firefly. Again, I can see the tags in the help files, so I'm not sure what I did wrong.

Could it be that the help you grabbed to build this is not the most current version?

**Comment by ejoliet** [comment]
> FITS header pop-up does NOT point to #id=tables
HiPS header pop-up does NOT point to #id=tables

- [ ] Will fix.

> PARTIALLY DONE stats pop-up points to #id=visualization.selectregion in irsaviewer but not firefly. I can see the tag visualization.selectregion in the relevant files, so I'm not sure what I've done wrong.

Can't see in onlnehlep of Firefly nightly build so it might not be correct in `firefly-help` github repos.

>"catalogs" blue tab// load own catalog does NOT point to #id=catalogs.owncatalogs (DNE in firefly, surprising to me)

- [ ] Will fix - it needs a fix in IFE, overwriting the helpid in Firefly (`#basics.searching`)

>"catalogs" blue tab// IRSA search does NOT point to #id=catalogs

The UI is different in Firefly: it opens with TAP searches not IRSA.

**Comment by lrebull** [comment]
Git claims that I am synched (and as far as I can tell, correctly synched) with master in both irsa-ui-help and firefly-help.

**Comment by lrebull** [comment]
The tags are defined in the app/src/toc/irsaviewer_toc.js and app/src/toc/firefly_toc.js. 
[snorlax:app/src/toc] rebull% grep catalogs.owncatalogs irsaviewer_toc.js 
            id: 'catalogs.owncatalogs',
[snorlax:app/src/toc] rebull% grep catalogs.owncatalogs firefly_toc.js 
            id: 'catalogs.owncatalogs',
The relevant code snippet is:
        {
            id: 'catalogs.owncatalogs',
            title: 'Your Own Catalogs',
            href: 'irsaviewer/catalogs.html#owncatalogs',
        },
And that anchor is definitely there in the html file:
[snorlax:app/src/toc] rebull% cd ../../../html/irsaviewer/
[snorlax:irsa-ui-help/html/irsaviewer] rebull% grep owncatalogs catalogs.html 
+<A href="#owncatalogs">Catalogs from Disk</A> <br>
<h3><a name="owncatalogs">Loading your own catalogs</A></h3><P>

**Comment by lrebull** [comment]
Ah, sorrry, meant to do that for visualization.selectregion, hang on.

**Comment by ejoliet** [comment]
yes, but not in Firefly-help.
Anyway.
I fixed the thing i can - See updated build at this link for IRSAViewer (Today there is a downtime ongoing, IBE didn't work for me as i m writing this) 

https://irsa-3498-update.irsakudev.ipac.caltech.edu/irsaviewer/

Firefly: https://fireflydev.ipac.caltech.edu/irsa-3498-update/firefly/

**Comment by lrebull** [comment]
AH! now i understand. fixed and checked back into git.
I agree, IBE isn't working for me either. Will try again after the blocktime.

**Comment by ejoliet** [comment]
IBE is back in dev.
Let me know if i need to fix anything else.
Otherwise, i can merge so we can move to the next step which is to implement the new anchors.

**Comment by lrebull** [comment]
Confirm all is fixed, except for my lost help anchor, which should be fixed in the version checked into git. Good to go.

**Pull request merged**
