### PR TITLE
FIREFLY-1548 fix-irsa-app-search-cleanup-issue

### PR DESCRIPTION
**Pull request by wmiipac**
View [ ticket](https://jira.ipac.caltech.edu/browse/FIREFLY-1548) for details.
By adding checks for none app searches from: `IRSA search tabs` and `External archive search tabs`, the previous search results are cleaned out for new app search only.
To test:
https://firefly-1548-sofia.irsakudev.ipac.caltech.edu/applications/sofia
https://firefly-1548-wiseirsakudev.ipac.caltech.edu/applications/wise
https://firefly-1548-ztf.ipac.caltech.edu/applications/ztf
https://firefly-1548-sha.irsakudev.ipac.caltech.edu/applications/Spitzer/SHA/
https://firefly-1548-euclid.irsakudev.ipac.caltech.edu/applications/euclid/

go to any of above IRSA app, ie. sofia, wise, ztf,
* make a position search (or any app search)
* navigate to a different search (without submit search), then go do a Catalog search (or any none app search), your catalog search result should be added as a tab to your previous search result.
* if you do a different app search, the results are for the new search, previous results are cleaned out.

### CODE REVIEW

**Review by loitly — COMMENTED** [review]
This may work for most cases now, but it all dependent on the `category` which can be anything.  Also, `upload` still does not work.  
@kpuriIpac merge a [commit](https://github.com/Caltech-IPAC/firefly/pull/1472/commits/6ceec78c346138645380a22c59f883cfa50c0528) which logic that may be problematic.
I need to ask him to see what he wanted to achieve.

One way to solve this issue to correctly populate 'activeSearch'.  I can push a commit to do this if you like.  But, I still won't know what the other logic is for in Kartik's commit.

**Comment by wmiipac** [comment]
> One way to solve this issue to correctly populate 'activeSearch'. I can push a commit to do this if you like.
sure, if you think there are better way to solve the problem, go ahead.

**Comment by wmiipac** [comment]
> This may work for most cases now, but it all dependent on the `category` which can be anything. Also, `upload` still does not work.

My approach is to exclude all none app searches, i.e. external searches, from cleanup step. Getting the true/correct `activeSearch`, would make more sense.

**Comment by wmiipac** [comment]
@loitly Kartik tested Euclid, we can merge this PR with your approval.

**Review by loitly — APPROVED** [review]
looks good.

**Pull request merged**
