### PR TITLE
DM-5276: Upgrade JS third party packages

### PR DESCRIPTION
**Pull request by loitly**
Main purpose is to upgrade babel to v6, React to v15, and latest version of webpack.
Things you should be aware of in React 15: https://facebook.github.io/react/blog/2016/04/07/react-v15.html
As far as I can tell, they are all fixed in this pull request.

Don't forget to `gradle purge` first.
The pull request should be built with a newly created node_module.

Also:
 - upgrade most packages to latest versions as well
    - see package.json diff for more details.
 - fixed warnings related to React upgrade
 - remove some of the unused packages
   - history
   - icepick
   - babel-eslint
   - react-tools
   - query
   - less
   - less-loader
   - jscs
   - eslint-config-airbnb

Original ticket:
https://jira.lsstcorp.org/browse/DM-5276

### CODE REVIEW

**Comment by ejoliet** [comment]
I've build the branch locally and did some random test. So far i can see one problem:
Some image tool dialog windows miss the 'x' close button when there is no a 'close' button explicitly, for example drawing layers, load regions ds9,etc .

**Comment by robyww** [comment]
the 'x' now shows up, pushed the fix.

**Comment by robyww** [comment]
The color picker api changed with upgrade.  Fixed our code to work with it.

**Comment by ejoliet** [comment]
Thanks for fixing those. I have found another problem: The compass rose doesn't show up, error log in the console says:

Uncaught TypeError: (0 , _DirectionArrowDrawObj.makeDirectionArrowDrawObj) is not a function

**Comment by ejoliet** [comment]
And stretch/color changes seems to be applied but shows a fail message on the image viewer, and the console throw the following log:
TypeError: (0 , _DirectionArrowDrawObj.makeDirectionArrowDrawObj) is not a function
    at makeCompass (http://localhost:8080/firefly/firefly-dev.js:112578:71)
    at getDrawData (http://localhost:8080/firefly/firefly-dev.js:112543:24)
    at DrawLayerFactory.getDrawData (http://localhost:8080/firefly/firefly-dev.js:88514:25)
    at getDrawData (http://localhost:8080/firefly/firefly-dev.js:97428:39)
    at http://localhost:8080/firefly/firefly-dev.js:97290:42
    at Array.forEach (native)
    at updateFromLayer (http://localhost:8080/firefly/firefly-dev.js:97289:20)
    at http://localhost:8080/firefly/firefly-dev.js:97247:25
    at http://localhost:8080/firefly/firefly-dev.js:55625:26
    at Array.map (native)

**Comment by robyww** [comment]
fixed the direction arrow failure

**Comment by robyww** [comment]
OK, it looks good as far as I know.  I sure we will find a couple of more issues.
  
@tgoldina needs to check the highcharts update.

**Comment by tgoldina** [comment]
It looks like Loi got the latest version of react-highcharts, and it appears to work as expected, no errors - I've checked both regular and binned plots.

**Comment by robyww** [comment]
Ok, I think it is good to merge.   We fix other issues as we find them.

**Review Complete.**

**Pull request merged**
