### PR TITLE
Firefly-1403: Fixes: #6 #7 #11 #13 #23 #24 #26 #27 #13.7 #30 #31 #33 …

### PR DESCRIPTION
**Pull request by robyww**
#### [Firefly-1404](https://jira.ipac.caltech.edu/browse/FIREFLY-1403): Fixes: 6 7 11 13 23 24 26 27 13 13.7 30 31 33 35 34 44 48 58 60

 - from page https://confluence.ipac.caltech.edu/display/IRSA/Testing+Feb+2024+-+Joy+UI%2C+mostly

#### Testing
 - https://firefly-1403-issues.irsakudev.ipac.caltech.edu/irsaviewer
 - https://firefly-1403-issues.irsakudev.ipac.caltech.edu/irsaviewer/dce
 - https://fireflydev.ipac.caltech.edu/firefly-1403-issues/firefly

check when confirmed

- [x] 6 
- [x] 7 
- [x] 11 
- [x] 13 
- [x] 13.7
- [x] 23 
- [x] 24 
- [x] 26 
- [x] 27 
- [ ] 30 
- [x] 31 
- [x] 33 
- [x] 35 
- [x] 34 
- [x] 44 
- [x] 48 
- [x] 58 
- [x] 60

### CODE REVIEW

**Comment by lrebull** [comment]
- Number 13 appears twice in your list.
- Number 12 in my page you said you couldn't reproduce, so I added a screenshot to explain.
- Number 13.7 is only partially fixed - the "e.g." under the time selection boxes in the temporal search are still italics.
- Number 30 is partially done - the header is changed, but no help button added (it's fine if you want to reject that part of it; i just need to know that you've rejected that part of it)
- Number 33 didn't catch all the changes. I can talk through them if you want. I made a detailed list here:
Screen Shot 2024-02-01 at 10 37 24 AM

**Comment by lrebull** [comment]
I can make DCE work now, but i have new bugs for you there; will add stuff to the confluence page.

**Comment by robyww** [comment]
@lrebull I finished 13.7 and 33

For 30 I don't think it need a help since the dialog acts more like a dropdown. Once you click is goes away.

**Comment by lrebull** [comment]
re: 30 - i am not sure that I, personally, understand the difference between "FITS Image Pixel, and "Zero based Image pixel" but i can put that in the docs anyway so that people can find it. 

agree 13.7 fixed 

33 - that one tooltip still has a period at the end of it.

**Comment by robyww** [comment]
ok, fixed the last of 33. I am going to merge and calling this ticket done.

**Pull request merged**
