### PR TITLE
IRSA-5xxx: multiple tickets: IRSA-5577, IRSA-5779, IRSA-5390

### PR DESCRIPTION
**Pull request by robyww**
#### IRSA-5xxx: multiple tickets: IRSA-5577, IRSA-5779, IRSA-5390

- [IRSA-5577](https://jira.ipac.caltech.edu/browse/IRSA-5577): fixed
- [IRSA-5779](https://jira.ipac.caltech.edu/browse/IRSA-5779): fixed
- [IRSA-5390](https://jira.ipac.caltech.edu/browse/IRSA-5390): fixed
- Added warning when BOX or REGION goes over limit (defaults to 30000), then show as catalog
- [IRSA-5897](https://jira.ipac.caltech.edu/browse/IRSA-5897): fixed

#### Testing
- https://irsa-5577-5779-5390.irsakudev.ipac.caltech.edu/applications/Spitzer/SHA
- Coverage should work better
- Warning when to many coverage Items (test: m16, .5 deg, PBCD, BCD)

#### Confirm Test
- [x] - IRSA-5577
- [x] - IRSA-5779
- [x] - IRSA-5390
- [x] - IRSA-5897

### CODE REVIEW

**Comment by lrebull** [comment]
ok... very interesting. When i loaded this the very first time, I put in m16, 0.5 degrees as suggested, and the first thing i did when it finished loading was click on 'coverage' ... and i tripped the same error as i got in Euclid the first time I loaded that. **the coverage tab never loaded**! I tried to remember what y'all tell me to do. i went to the browser console and got this:
Screenshot 2024-10-16 at 2 35 47 PM

and then I also went to the "web developer tools" and that was enough to get the coverage tab to render. this is what that looked like right after that loaded:
Screenshot 2024-10-16 at 2 36 58 PM

**Comment by lrebull** [comment]
oh, and then the console updated:
Screenshot 2024-10-16 at 2 38 38 PM

**Review by wmiipac — APPROVED** [review]
Tested. Working as expected. Thanks for fixing.

- PBCD and BCD overlay look good, like the newly added warning sign and message!

- Spectrum (PBCD and BCD) wavelength unit set to microns.

**Comment by lrebull** [comment]
Now for the real purpose of this ticket.

**Comment by wmiipac** [comment]
I didn't see what @lrebull  saw in my browser console

**Comment by lrebull** [comment]
Now for the real purpose of this ticket, part 1:
I like the warnings. Wording needs help. Here are some suggestions (note punctuation, not just words!):

> Coverage Warnings:
> Level 1 (BCD) has too many rows to show the boundaries individually in this image, so they are shown as just the centers of the BCDs (like a catalog would be shown). To see the individual boundaries, filter down your results to below 30,000 rows. 

I imagine that you have other warnings for Level 2, etc.; I've just not seen them yet.  You should propagate the word changes accordingly. 

And here is an additional wrinkle. Because we do have the hierarchical catalog overlays installed here, now it's potentially *super* confusing -- for example, I'm staring at this:  
Screenshot 2024-10-16 at 2 47 48 PM
and if I didn't know about the hierarchical catalogs, I'd be perplexed by the additional grid and numbers. Even being braced for it, I wasn't 100% sure that the HEALPix grid hadn't been turned on. I'm thinking we have to have an additional warning, at least for this tool (and maybe SOFIA? because it might also trip this though not as easily as Spitzer); here are some words:

> Catalogs above a dynamically-adapting threshold are shown as a 'cell' with a number to indicate the number of sources within that cell. Zoom in to see smaller cells until individual sources are shown; see the layers pop-up to change how this is shown (and the size of the cells), and see the online help for more information.

**Comment by lrebull** [comment]
"Real purpose of this ticket", part 2 -- the spectra: this works great; i couldn't confuse it, and i tried !

**Comment by wmiipac** [comment]
> I imagine that you have other warnings for Level 2, etc.; I've just not seen them yet. You should propagate the word changes accordingly.

with the position search range up to 1 degree, it is unlikely PBCD will get more than 30,000, maybe there are some dense area could hit 30,000?

**Comment by lrebull** [comment]
OK.. 'new private window' on this build, M16, 0.5 degrees, tick all tabs, search... go to 'data coverage'... and it never loads. here is what i see:
Screenshot 2024-10-17 at 9 12 58 AM

**Comment by lrebull** [comment]
in case it helps, here is what i see when i click "multiprocess (slower)" at the top of that window:
Screenshot 2024-10-17 at 9 15 23 AM

**Comment by lrebull** [comment]
About the warnings. We need to make sure that the text is structured in parallel and is clear/consistent. (and all the words should be spelled right - there is a "wth" in there now.) If you want to use the "category in brown/details in black" structure, great, but let's be consistent about it. And it's not just "coverage like catalogs" because catalogs are being shown here too.
here's some updated text. 

[warnings.docx](https://github.com/user-attachments/files/17416030/warnings.docx)

**Comment by lrebull** [comment]
IRSA-5897 seems to be fixed.

**Pull request merged**
