### PR TITLE
DM-14157: hips/fits/aitoff switching

### PR DESCRIPTION
**Pull request by robyww**
- buttons to move between hips/fits/aitoff
  - zoom switching now includes allsky in algorithm
  - auto check box to switch on zoom
  - zoom level switch to field of view
  - fixed: FOV when image zoomed level is really small
  - fixed: order of buttons
  - fixed: context toolbar going away when in different context modes
  - ButtonGroup option for RadioGroupInputFieldView

_to test:_

 - do catalog search, then switch between hips and fits
 - try the auto button and zoom
 - do a catalog search with m4, then m1
 - switch between hips, fits, aitoff
 - try auto button and zoom
 - try tooltip over field of view for both hips and fits
 - notice that there is only field of view, not zoom level

### CODE REVIEW

**Comment by cwang2016** [comment]
@trey Here are two cases I observed, needing your verification. 
case 1, 
do catalog search on m31
then switch the selection between HiPS and Fits, the FOV number is changed every time switching to HiPS, and FOV on FITS follows the change accordingly. 

question: FOV on HiPS is changed every time when it is re-selected after FITS? 

case 2, 
do catalog search on m31, got HiPS image, FOV 13 arcmin
next do catalog search on m4, got HiPS image, FOV 171 deg
next do catalog search on m1, radius 100 arcsec, got aitoff 
switch to HiPS, got FOV 171 deg
switch to FITS, got FOV 14 arcmin, then HiPS, got FOV 19 arcmin
switch to aitoff, then HiPS, got FOV 171 deg. 

question: FOV on HiPS is different depending on if it is selected after Aitoff or FITS?

**Comment by trey** [comment]
@cwang2016 I think you have the wrong Trey. :)

**Comment by cwang2016** [comment]
Review completed. ButtonGroup works well. Just having the concern regarding FOV values as switching among HiPS/FITS/Aitoff.

**Comment by trey** [comment]
Still the wrong @trey. Please notify the correct Trey. I beg you.

**Comment by cwang2016** [comment]
@robyww 
case 1,
do catalog search on m31
then switch the selection between HiPS and Fits, the FOV number is changed every time switching to HiPS, and FOV on FITS follows the change accordingly.

question: FOV on HiPS is changed every time when it is re-selected after FITS?

case 2,
do catalog search on m31, got HiPS image, FOV 13 arcmin
next do catalog search on m4, got HiPS image, FOV 171 deg
next do catalog search on m1, radius 100 arcsec, got aitoff
switch to HiPS, got FOV 171 deg
switch to FITS, got FOV 14 arcmin, then HiPS, got FOV 19 arcmin
switch to aitoff, then HiPS, got FOV 171 deg.

question: FOV on HiPS is different depending on if it is selected after Aitoff or FITS?

**Comment by cwang2016** [comment]
@robyww 
I push a fix to show the hips list popup with the highlighted row in sync with the hips image after catalog search.

**Comment by robyww** [comment]
Thanks for the commit @cwang2016

**Comment by robyww** [comment]
@cwang2016 thanks for the testing:

**case1**: _fixed_
**case2**: 
 - This is fixed as it is similar to case 1.  
 - I made switching to aitoff to always go to the full image.  Aitoff is very hard to match up.  
 - When switching from aitoff to fits it get the maximum size FITS image of the center point on the screen.  
  - When switching to HiPS it is similar, maximum size centered on the Aitoff center point.

So 'from Aitoff' always tries to line up the point, 'to Aitoff' always just shows the Aitoff full screen. I hope this is good enough for the users.

**Pull request merged**
