### PR TITLE
Firefly-460: Add file analysis & more visualization to data products viewing

### PR DESCRIPTION
**Pull request by robyww**
Firefly-460: Add file analysis & more visualization to data products viewing

  - Add new controller for the DataProductsType
  - add file FileAnalysis
  - create UI for FileAnalysis results
  - add charts to MultiProduct viewer
  - work on framework for recognizing data
  - refactor and cleanup
  - Improve file upload to include WebPlotRequest
  - Improve file upload to send progress feedback
  - clean up for sofia
  - support tar, pdf on file analysis server side
  - extension improvements with upload
  - catch pdf, tar, png files on the client side if posible without file analysis
  - improve messaging when there in only one download
  - Supported views: table, chart, table/chart flip, image, png, message, download (tar)
  - VOAnalyzer now does all the data product recognition - all case insensitive
  - tested with wise, fixed bugs

https://jira.ipac.caltech.edu/browse/FIREFLY-460

### All testing

- Data products will show as you click on the related data products table.
- With data link use the `More...` dropdown.
- Any file that has more than one data product will have a `In File...` dropdown

 https://irsawebdev9.ipac.caltech.edu/firefly-460-file-analysis/firefly/
###  Upload Test

1. Go to Upload panel
1. Load: http://web.ipac.caltech.edu.s3-us-west-2.amazonaws.com/staff/roby/data-products-test/data-product-test-ipac-table.tbl
1. Click on the rows

### Obscore Simple Test
1. Goto the `Tap Searches Menu`
1. Choose MAST
1. Choose ivoa / ivoa.obscore
1. choose m31 / 100 arcsec  (and try other targets)
1. click around you will see some images
1. now filter `obs_collection` on FUSE
1. click around about half way down the page, you will see some charts show up
1. switch between tables and charts using the buttons on toolbar

### Obscore Datalink Test
1. Goto the `Tap Searches Menu`
1. Choose CADC
1. Choose ivoa / ivoa.obscore
1. choose m31 / 100 arcsec  (and try other targets)
1. click around only has stuff that can be downloaded.
1. sort on obs_publisher_did
1. now you click around and will see images
1. try the `More` dropdown

### Sofia Test
ife PR: https://github.com/IPAC-SW/irsa-ife/pull/101
https://irsawebdev9.ipac.caltech.edu/firefly-460-file-analysis/applications/sofia/
1. Do an all sky search
1. Every tab is able to show some sort of data products
1. Not HAWC+: some of the files also have tables (click on the first line after the red). You will see the `In File...` dropdown

### Known bug
Expansion does not work for charts and tables in the DataProductsViewer.  This will be fix in a separate PR or a patch to this one.

## Code Review details

Basic flow:

- Tables are watch by DataProductsWatcher.js
- If the table is a data Products table then the DataProductsFactors determines the correct converter. the only ones that matter of this PR are ObsCore and UNKNOWN
- The converter turns a table row into `DataProductsDisplayType`
- A `DataProductsDisplayType` may have a menu with other  `DataProductsDisplayType`  (data link case)
-  A `DataProductsDisplayType` may have a fileMenu with of  `DataProductsDisplayType`  (result of file analysis)
- The DataProductCntlr maintains the `DataProductsDisplayType` in the store
- `MultiProductViewer` will render when data products
- Rendering requires two two steps:
   - rendering the correct react components
   - calling the activate function passed in the DataProductsDisplayType object.
   - The activate function will call dispatchTableSearch, dispatchPlotImage, etc.

Best files to look at:
- DataProductsCntlr.js
- MultiProductViewer.jsx
- ObsCoreConverter.js
- MultiProductFileAnalyzer.js
- PartAnalyzer.js
- DataLinkProcessor.js
- DataProductsType.js
- AnyFileUpload.java

### CODE REVIEW

**Comment by loitly** [comment]
While testing SOFIA HAWC+ data, cannot switch to `In File` Table:.  Table loaded with error: Failed to retrieve data.

**Comment by robyww** [comment]
> While testing SOFIA HAWC+ data, cannot switch to In File Table:. Table loaded with error: Failed to retrieve data.

That table is not read because of an error given by star table reader.  I think the table is bad.  There are other  HAWC+ that read correctly.

**Comment by robyww** [comment]
@loitly @ejoliet I am fixing all the issues found except the following:

#### _from @loitly_ 
> maybe display information about the file, like name, size, mod date, etc.. then option to download.

There is no general way that we know the size. Sometimes with tar, pdf, gz we attempt not to even go though file analysis. We don't know much about the file beyond the url.

#### _from @ejoliet_ 
> In Safari, the chart X-axis title is not visible, probably a size issue of the panel frame in the parent element

This is really a charting issue. I think it should be a separate ticket

#### _from @ejoliet_
> Expanding the data product chart expands the other main chart of the main search result table instead.

This is the existing bug that I describe in my PR write up.  I already talked to @loitly about it. We are going to make a separate ticket

####  _from @ejoliet_
> would be great if we can get a split pane and icon

I agree. I think I would be a good idea. It would not be hard to do.

####  _from @ejoliet_
> the drop-down menu title could be more helpful than 'In File'

Really the dropdown names `More...` and `In File...` are just place holders. I open to suggestions. We will probably get some after user testing.

In general the whole Data products viewing UI will probably get some feedback so we will need to make changes. The good news is that the react/UI part of this PR is a small part of the total work.
The whole UI is in `MultiProductViewer.jsx` which is only one of the 35 files in the PR and only about 315 lines.

**Comment by loitly** [comment]
I found something else:
Start with `Images` search;  wise m31 
Then `TAP Searches`; MAST ivoa obscore m31 100
Select `Images` tab.  As you move around the ivoa.obscore table, the selected wise image to pan out of place, showing `Center Plot ` with `Recenter` button next to it.

**Comment by ejoliet** [comment]
Also, another 'side effect' in SOFIA, the row in pink background have this message now:
'No displayable data available for this row: Request failed with status 500: http://localhost:8080/applications/sofia/sticky/CmdSrv?cmd=upload'

which should be another one, that is displayed in white background - @deannaji might want to look at it now or after you merge. 

Another thing that i'm seeing is confusing for me (but maybe is not the expected behavior), when an image is displayed, there are 2 icons single and multiple grid images, i thought those were belonging to the file in that highlighted row but is actually a grid of all the images from the result table.  I'm not sure is consistent with 'in file' where it shows the product for the particular row. 
is it?

**Comment by robyww** [comment]
@ejoliet 

> Also, another 'side effect' in SOFIA, the row in pink background have this message now:

That should not happen. I will working on fixing that.  I don't think it was doing that  last week. I probably just broke it.

**Comment by robyww** [comment]
@loitly 
> I found something else:
Start with Images search; wise m31
Then TAP Searches; MAST ivoa obscore m31 100
Select Images tab. As you move around the ivoa.obscore table, the selected wise image will pan out of place, showing Center Plot with Recenter button next to it.

I am sure this is a side affect of out "center on selected point" feature.  The keeps coming up at unexpected times.  Let me look at what I can do.

**Comment by robyww** [comment]
@loitly 

>I am sure this is a side affect of out "center on selected point" feature. The keeps coming up at unexpected times. Let me look at what I can do.

I changed my mind. I am not going to do anything about this.  It is not a bug. It is really working the way it is suppose too.  If the use does not like it he can turn it off (`Pan by table row`). I don't think trying to guess what the use wants here is a good idea or that I can even get it right.

**Pull request merged**
