### PR TITLE
DM-6980:  Fix PNG creation for marker

### PR DESCRIPTION
**Pull request by cwang2016**
Fixing method: 
Marker size is represented by a small pure number (magnitude of thousandth) in term of world coordinate (J2000). World coordinate is a hint to set the size value with 'degree' unit, otherwise the size value was treated with 'pixel' unit, too small to be shown in the PNG.

### CODE REVIEW

**Comment by cwang2016** [comment]
test:
select any image, click 'marker/footprint' button, select 'Add Marker', click 'save fits, png...' button, and choose 'png' for download, check if the marker is shown in the download PNG.

**Comment by xiuqin** [comment]
1. The color of the marker does not show up in PNG.
2. The Marker label does not  show in PNG 
3. The catalog overlaid on image was square on screen, but cross (X) on PNG.

**Comment by cwang2016** [comment]
More updates are added to fix the issues regarding PNG download from both image search and catalog search, including 
- showing the marker added from marker/footprint dropdown list.
- showing the right color as color changed from drawing layer popup. 
- showing the marker with the right color and right point shape from catalog search.
- showing the marker/footprint label.

**Comment by ejoliet** [comment]
I have tested this fix in http://localhost:8080/firefly/demo/ffapi-highlevel-test.html but i don't see the fix. Am i doing something wrong for testing?

See attached image on left the PNG downloaded and right the browser viewer.
screen shot 2016-09-19 at 3 18 41 pm

**Comment by ejoliet** [comment]
Update: the fix works in firefly viewer. Maybe it doesn't in the API mode?

**Comment by ejoliet** [comment]
Works also great in IRSAVIewer, i've checked.

Really minor: compass rose is included in PNG but not the labels 'N', 'E'.

**Comment by cwang2016** [comment]
more update: 
change the color  of compass labels, from 'black' to 'red'.

**Pull request merged**
