### PR TITLE
Dm 13420 table error message

### PR DESCRIPTION
**Pull request by loitly**
these 2 are duplicate of #13420
https://jira.lsstcorp.org/browse/DM-13591
https://jira.lsstcorp.org/browse/DM-13591

also fixed:
https://jira.lsstcorp.org/browse/DM-13592
- tooltips missing for votable
https://jira.lsstcorp.org/browse/DM-13594
- in embedded mode, the `reset` button in table options submits enclosed form when clicked.
https://jira.lsstcorp.org/browse/DM-13595
- in embedded mode, input fields may trigger form submit if used within a `form` tag.
https://jira.lsstcorp.org/browse/DM-13597
- same as #13595

The changes are not big.  But, it's a bit hard to review.  
The error messages, you'll be able to see in any table.
For the embedded mode, I've deployed this version into k8s at:
      https://irsawebdev9.ipac.caltech.edu/dm-13420/firefly/ 
I'll ask Jeff to use this instance in his dev environment to test the rest.

UPDATE:  Jeff pointed his dev env to this instance.  You can see it at https://dev.ned.ipac.caltech.edu

### CODE REVIEW

**Comment by lrebull** [comment]
I'm still trying to figure out how to make this whole github review process work; apologies for the delay.

If I'm understanding correctly, you want me to look at the tables that are loaded in this instance:
https://irsawebdev9.ipac.caltech.edu/dm-13420/firefly/
right?

I load the tool at that link. I search on M16, all defaults, WISE+2MASS+SEIP.
It returns with images. 
I click on the catalogs tab.
The first indication of trouble is that when I do so, the default WISE catalog comes up in the interface to select a catalog, but this appears in the list of fields at the bottom from which I could impose filters:
Failed to fetch catalog fields: BadSqlGrammarException:StatementCallback; bad SQL grammar [select * from data limit 0]; nested exception is java.sql.SQLSyntaxErrorException: user lacks privilege or object not found: DATA from:null

If I plunge onwards and ask it for a polygon covering the image, I get this:
Table Load Error:
java.io.IOException: Catalog Query Failed - network Error

If I'm supposed to be testing the tables, I've got a problem, because I can't load tables. Help?

**Comment by loitly** [comment]
> is the "filters" text area in the table setting panel working or is just a log text output? i'm writing there filter but i don't get it executed, was this always that way?

This is broken ever since switching to tables backed by database.  A new and improved  filter editor will happen soon.

>if i use string filter on a numerical column, i get "column not found..."

This is fixed

> one of the ticket mentioned a way to see the exception for debugging...

Not worked on because it's for debugging only, and we should be thinking of that as a whole and not just table.

>If i search on NED catalog (last tab on the right of the catalog search form,) and go to setting panel and then close it, there is an error message related to "details" column: unexpected token: __NOT_A_VALID_DATA___ "Details" __NOT_A_VALID_DATA___

This is fixed

@ejoliet , please review again.

**Comment by lrebull** [comment]
OK, sorry, still confused. How is it 'fixed' if it's not working? Is it just me (again)? is it fixed on some other machine or port?

**Comment by lrebull** [comment]
Oh, sorry, you were replying to @ejoliet ..not me. Got it.

**Comment by loitly** [comment]
@lrebull , bad timing.  WISE is down at the moment.  ISG is aware of it.  2MASS works.
As for review, you should see a 'add your review' button at top-right corner of the page.
You can request for changes, approve, or just leave a comment.  Leaving a comment as you did is fine as well.

**Comment by lrebull** [comment]
Trying again this morning now that WISE is back.
I'm still super confused as to what I am supposed to test vs. ignore. Like the prominent "Firefly" in the upper left ... is that a proposed change for ops or just a loose end in this working deployment?

The original message above says:

> these 2 are duplicate of #13420
> https://jira.lsstcorp.org/browse/DM-13591
> https://jira.lsstcorp.org/browse/DM-13591

But these are the same two tickets... 
13591 does seem to be fixed in that I get a more elegant error message and when I go back, my prior filters are still there, so that's awesome. 
13420 seems to be largely the same thing, and does seem to be fixed as the ticket describes.

*ah, but as I'm continuing to test, clicking on filter and whatnot, it eventually froze my session. I got, from Firefox, "A webpage is slowing down your browser. What would you like to do?"  It seems to have gotten stuck on plotting, even though I have a small table. Clicking "back" doesn't do anything until it loads the plot.  If it gets stuck plotting, everything is hosed everywhere else in the web page (like, I can't reload the table, I can't turn on the filtering row, I can't click on the gears)...

> also fixed:
> https://jira.lsstcorp.org/browse/DM-13592

I do see tooltips, but these are IPAC tables, right? Not VO tables? Those are something different, I am sure. I thought FIrefly worked with IPAC table files. I thought that even if I did a VO search, the results are still IPAC tables .. at least they are when I save them to disk...  If this just means a VO search, I haven't been able to successfully do a VO catalog search in literally months. Usually for me it works just for a few days around when I write documentation, and then it's broken until some later date, and it's usually not our fault, but something down/changed at the other end(s). This morning, it says (on ops, when I try to do a VO catalog search): Failed to load table. edu.caltech.ipac.firefly.server.query.DataAccessException: query failed - network error

>     tooltips missing for votable
>     https://jira.lsstcorp.org/browse/DM-13594

this says "filtering from the table editor".. what is the "table editor"?
From a regular table, I can filter. I can cancel the filter and have the table reload. I can filter again with a bogus request (Like ra > H) and have it give me a sensible error message; when I go back, it reloads EVERYTHING, not just the table. I'm not sure if this is what this ticket is talking about or not in the reference to ENG-632.

>     in embedded mode, the reset button in table options submits enclosed form when clicked.
>     https://jira.lsstcorp.org/browse/DM-13595

What is "embedded mode"? 
Yes, I can click on the reset button in the table options and it reloads the page but keeps me on that catalog tab. At least, I think that is what the ticket is saying.

>     in embedded mode, input fields may trigger form submit if used within a form tag.
>     https://jira.lsstcorp.org/browse/DM-13597
>     same as #13595

What is "embedded mode"? Ticket says "table editor not filter panel" and I don't know what that is either. (What is "table editor" and what is "filter panel"? There is a filter row..? do you mean the table options pop-up?) The comments say things about using tab rather than enter, but it's not clear to me which is supposed to work now. Both seem to work for using the filter row, and the table options pop-up, but I'm not sure what the filter panel is.

**Pull request merged**
