### PR TITLE
Dm-10241 Fix the rendering of east arrow in the North/East compass

### PR DESCRIPTION
**Pull request by cwang2016**
This development fixes the rendering of the East arrow line in the North/East compass, making the direction of the East arrow perpendicular to the North arrow line.

test: 
please refer to the compass on DS9 for the following image search,. 
- from Firefly, get image by setting RA=45, DEC=89 and selecting IRAS with 5 degree cutout,
  add grid and the North/East Compass. 
- download the fits image, and open it from DS9.
- add grid and compasses at various locations  in DS9
- move the image in Firefly to see the compass shown on various locations and compared the compass to that shown on DS9.

### CODE REVIEW

**Comment by ymeiymei** [comment]
Reviewed but found some time our firefly compass doesn't point to North. See attached image.
screen shot 2017-04-26 at 8 56 22 am

**Comment by ymeiymei** [comment]
After cleaning the browser history, the compass works fine.

Review is finished.

**Comment by cwang2016** [comment]
additional update:
fix the east arrow direction in thumbnail image.

**Comment by stargaser** [comment]
Re-review completed. The thumbnail compass now renders properly. Looks good!

**Pull request merged**
