### PR TITLE
IRSA-2017 Add ZTF image to irsaviewer image search

### PR DESCRIPTION
**Pull request by wmiipac**
Add ZTF image to irsaviewer image search panel. Code change in both firefly and ife.
ku8 build:
https://irsawebdev9.ipac.caltech.edu/irsa-2017/irsaviewer/

Note:  PTF image search is added into firefly panel, but not in irsaviewer

### CODE REVIEW

**Comment by lznakano** [comment]
Wei,

You build does not work either.  It seems building Firefly OK but irsaviewer.   I built many times but none worked.


On May 20, 2019, at 12:26 PM, Wei Mi <notifications@github.com<mailto:notifications@github.com>> wrote:


Add ZTF image to irsaviewer image search panel. Code change in both firefly and ife.
ku8 build:
https://irsawebdev9.ipac.caltech.edu/irsa-2017/irsaviewer/

Note: PTF image search is added into firefly panel, but not in irsaviewer

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/Caltech-IPAC/firefly/pull/806

Commit Summary

  *   IRSA-2017 Add ZTF image to irsaviewer image search

File Changes

  *   M config/app.config<https://github.com/Caltech-IPAC/firefly/pull/806/files#diff-0> (4)
  *   M src/firefly/config/app.prop<https://github.com/Caltech-IPAC/firefly/pull/806/files#diff-1> (3)
  *   M src/firefly/html/test/template.html<https://github.com/Caltech-IPAC/firefly/pull/806/files#diff-2> (2)
  *   M src/firefly/java/edu/caltech/ipac/astro/ibe/datasource/PtfIbeDataSource.java<https://github.com/Caltech-IPAC/firefly/pull/806/files#diff-3> (5)
  *   M src/firefly/java/edu/caltech/ipac/astro/ibe/datasource/ZtfIbeDataSource.java<https://github.com/Caltech-IPAC/firefly/pull/806/files#diff-4> (59)
  *   M src/firefly/java/edu/caltech/ipac/firefly/resources/irsa-image-master-table.csv<https://github.com/Caltech-IPAC/firefly/pull/806/files#diff-5> (850)
  *   M src/firefly/java/edu/caltech/ipac/firefly/server/persistence/IBEUtils.java<https://github.com/Caltech-IPAC/firefly/pull/806/files#diff-6> (27)
  *   M src/firefly/java/edu/caltech/ipac/firefly/server/visualize/imageretrieve/ServiceRetriever.java<https://github.com/Caltech-IPAC/firefly/pull/806/files#diff-7> (29)
  *   M src/firefly/java/edu/caltech/ipac/firefly/visualize/WebPlotRequest.java<https://github.com/Caltech-IPAC/firefly/pull/806/files#diff-8> (18)
  *   M src/firefly/java/edu/caltech/ipac/visualize/net/IbeImageGetter.java<https://github.com/Caltech-IPAC/firefly/pull/806/files#diff-9> (35)
  *   M src/firefly/java/edu/caltech/ipac/visualize/net/ImageServiceParams.java<https://github.com/Caltech-IPAC/firefly/pull/806/files#diff-10> (2)
  *   A src/firefly/java/edu/caltech/ipac/visualize/net/PtfImageParams.java<https://github.com/Caltech-IPAC/firefly/pull/806/files#diff-11> (40)
  *   A src/firefly/java/edu/caltech/ipac/visualize/net/ZtfImageParams.java<https://github.com/Caltech-IPAC/firefly/pull/806/files#diff-12> (40)
  *   M src/firefly/js/ui/FitsDownloadDialog.jsx<https://github.com/Caltech-IPAC/firefly/pull/806/files#diff-13> (6)
  *   M src/firefly/js/visualize/WebPlotRequest.js<https://github.com/Caltech-IPAC/firefly/pull/806/files#diff-14> (40)
  *   M src/firefly/js/visualize/ui/ImageSelectPanel.jsx<https://github.com/Caltech-IPAC/firefly/pull/806/files#diff-15> (4)
  *   M src/firefly/js/visualize/ui/ImageSelectPanelProp.js<https://github.com/Caltech-IPAC/firefly/pull/806/files#diff-16> (2)
  *   M src/firefly/js/visualize/ui/ImageSelectPanelReducer.js<https://github.com/Caltech-IPAC/firefly/pull/806/files#diff-17> (4)
  *   M src/firefly/js/visualize/ui/ImageSelectPanelResult.js<https://github.com/Caltech-IPAC/firefly/pull/806/files#diff-18> (8)

Patch Links:

  *   https://github.com/Caltech-IPAC/firefly/pull/806.patch
  *   https://github.com/Caltech-IPAC/firefly/pull/806.diff

**Comment by ejoliet** [comment]
@wmiipac Looks like it's working (we should ask Luisa to look at it also) but we probably need to change labels. For example, we should follow the same labels we use for others, such as `FILTER name (filter value and unit)` - need to ask Vandana or Luisa for those input.
Also, the image label should be probably shorter, right now it displays: "`ZTF Reference Image filter zr` "and so on and so forth but maybe we should have: `ZTF Ref. Img. zr` or something shorter that make sense and has useful information for users. Again, Vandana should give feedback on this. 

The functionality is there so i'm ok to approve it. Maybe wait for feedback from scientist before merging.
Thanks.

**Comment by lrebull** [comment]
I'm not 100% sure that this is what you wanted me to do (following comments above, how can the changes be made only to firefly and not IRSA Viewer, but yet i can see them from the IRSA Viewer in your build??), but here is some feedback:
(1) PTF and ZTF should appear near each other in the "MISSION" list
(2) Both should show up when 'compilation' is selected under "project type" on the left; there's a lot of southern hemisphere (and a small patch in the northern hemisphere) that isn't in the surveys.
(3) In parallel with many of the other program names, the entries on the right hand side should be "PTF: Reference Images" and "ZTF: Reference Images"... at least I think it should be plural. The colon is explicitly in parallel to the other programs, and since there are more PTF/ZTF products than just reference images, this seems correct to me.
(4) The channel descriptions should be different.
ZTF: Reference Images
[ ] zr [ ] zg 
should be instead
[ ] ZTF g (xx Angstroms) [ ] ZTF r (xx Angstroms) 
(I'm working on getting you the values for 'xx'; also note that it's the shorter wavelength first)
and similarly:
PTF: Reference Images
[ ] 1  [ ] 2
should be instead
[ ] PTF g (xx Angstroms) [ ] PTF R (xx Angstroms) 
(again, I'm working on getting you the values for 'xx'; also note that it's the shorter wavelength first)
(5) image labels, again, in parallel to other surveys:
"ZTF Reference Image filter zr" --> "ZTF: Reference images ZTF r"
"ZTF Reference Image filter zg" --> "ZTF: Reference images ZTF g"
"PTF Reference Image filter 1" --> "PTF: Reference images PTF g"
"PTF Reference Image filter 2" --> "PTF: Reference images PTF R"
Important note, 5a: Based on my exploration of image headers, things that are returned from PTF filter 1 AND PTF filter 2 both have filter "G" in their FITS headers; we need to sort out exactly what it's doing and fix the filters and the interface and the image labels accordingly.
Important note, 5b: I was under the impression that the labels couldn't be shorter than the name that appears on the search page, but in the above, Emmanuel suggests that the labels be shortened. Sure, change it to "ZTF: Ref Img ZTF r" (and similar for the other images) if you can. But the filter names really do appear to formally be "ZTF r" and "ZTF g." For PTF, they just call the filter names "g" and "R"...except for in the FITS headers, which appear to be both "G" (whimper)...

**Comment by lrebull** [comment]
[ ] ZTF g (4750 Angstroms) [ ] ZTF r (6470 Angstroms)
still working on PTF

**Comment by wmiipac** [comment]
Great, that's the exactly the feedback I need. I may take PTF out from the mission list for now. After all, this is the ticket for ZTF only. Thanks!

On 5/23/19 8:51 AM, lrebull wrote:

I'm not 100% sure that this is what you wanted me to do (following comments above, how can the changes be made only to firefly and not IRSA Viewer, but yet i can see them from the IRSA Viewer in your build??), but here is some feedback:
(1) PTF and ZTF should appear near each other in the "MISSION" list
(2) Both should show up when 'compilation' is selected under "project type" on the left; there's a lot of southern hemisphere (and a small patch in the northern hemisphere) that isn't in the surveys.
(3) In parallel with many of the other program names, the entries on the right hand side should be "PTF: Reference Images" and "ZTF: Reference Images"... at least I think it should be plural. The colon is explicitly in parallel to the other programs, and since there are more PTF/ZTF products than just reference images, this seems correct to me.
(4) The channel descriptions should be different.
ZTF: Reference Images
[ ] zr [ ] zg
should be instead
[ ] ZTF g (xx Angstroms) [ ] ZTF r (xx Angstroms)
(I'm working on getting you the values for 'xx'; also note that it's the shorter wavelength first)
and similarly:
PTF: Reference Images
[ ] 1 [ ] 2
should be instead
[ ] PTF g (xx Angstroms) [ ] PTF R (xx Angstroms)
(again, I'm working on getting you the values for 'xx'; also note that it's the shorter wavelength first)
(5) image labels, again, in parallel to other surveys:
"ZTF Reference Image filter zr" --> "ZTF: Reference images ZTF r"
"ZTF Reference Image filter zg" --> "ZTF: Reference images ZTF g"
"PTF Reference Image filter 1" --> "PTF: Reference images PTF g"
"PTF Reference Image filter 2" --> "PTF: Reference images PTF R"
Important note, 5a: Based on my exploration of image headers, things that are returned from PTF filter 1 AND PTF filter 2 both have filter "G" in their FITS headers; we need to sort out exactly what it's doing and fix the filters and the interface and the image labels accordingly.
Important note, 5b: I was under the impression that the labels couldn't be shorter than the name that appears on the search page, but in the above, Emmanuel suggests that the labels be shortened. Sure, change it to "ZTF: Ref Img ZTF r" (and similar for the other images) if you can. But the filter names really do appear to formally be "ZTF r" and "ZTF g." For PTF, they just call the filter names "g" and "R"...except for in the FITS headers, which appear to be both "G" (whimper)...

**Comment by lrebull** [comment]
[ ] PTF g (4810 Angstroms) [ ] PTF R (3107 Angstroms)

**Comment by ejoliet** [comment]
@wmiipac after Luisa test it and all is good, be careful when merging the `irsa-image-master-table.csv` file ;-)

**Pull request merged**
