### PR TITLE
DM-8449 resolve LSST catalog search panel running bugs

### PR DESCRIPTION
**Pull request by cwang2016**
The development fixed the following issues:
1.Catalog polygon search doesn't work (wrong parameters passed)
2.Can not switch to catalog search after image search fails on creating the plot.
3.update the title of searched image table

### CODE REVIEW

**Comment by cwang2016** [comment]
Test: 
localhost:8080/firefly/lsst-pdac-triview.html
1. select catalogs->Deep Source->target: 9.469, -1.152, method search: box, radius: 0.01 deg->search, then change method search to: polygon-> search. 
2. select image->Science CCD Exposure, target: 0, -1, size: 1 deg -> no image plot, then switch selection to catalogs and deep coadd, check spatial search panel for catalog
3. select image -> Deep source -> target (0, -1) , size 1 deg, search, 
     then target (1, -1), size 1 deg, search, check the title of searched image table in triview.

**Comment by ymeiymei** [comment]
1 and 3 passed!

For Case 2. The image title for the search type "image covers entire search region" only shows the box size, no info about the RA and Dec. Need some fix?

**Comment by cwang2016** [comment]
ra, dec numbers are added into the title  for all search type of image table. (center, covers, and enclosed).

**Comment by ymeiymei** [comment]
Test is passed. The RA and Dec information is added to the image title for all the search types.

Good job!

**Pull request merged**
