### PR TITLE
DM-5283:fixed 2-color flux readout  layout issue and FitsHeader's issues

### PR DESCRIPTION
**Pull request by lznakano**
Please check and let me know if both FitsHeader and MouseReadout look OK.  Thanks!

### CODE REVIEW

**Comment by xiuqin** [comment]
The ticket number is wrong in the branch name. It should be DM-5820 if you want to read the ticket.

**Comment by xiuqin** [comment]
issue: 
- The FITS header popup window does not show when I made a two color or one color image.
- The position readout need to be a little longer to be able to display 12h12m12.12s +12d12m12.12s
   It overlaps with the image name sometimes. Try WISE m31, with mouse around center of the target.

**Comment by robyww** [comment]
- I saw the same as Xiuqin, two color does not come up with FITS header
- On safari, the resize indicator is better, however, there is still an extra one.
- I did not see the text wrapping issue, @loitly did, so I am not sure which test to use.  Maybe he can try it.

**Comment by lznakano** [comment]
I emailed the error messages on Friday night.  There is a java server side issue which caused the two-color FitsHeader does not show up.  The issue is not from the client (javascript side).  FYI

**Comment by lznakano** [comment]
Trey,

I changed the text font type and the background color.  Please take a look and let me know if you spot anything else.  

Thanks!

**Comment by lznakano** [comment]
Xiuqin and Trey,

Please verify it again to see if everything looks OK.  Thanks!

**Comment by robyww** [comment]
put this in hipchat but repeating it here:
I have looked.  You still don't have the  background set to look like the standard header dialog, it is whiteish
goto line 61 of FitsHeaderView and set the background to #e3e3e3; then remove any color style that override them in the tab case

**Comment by robyww** [comment]
Looks good.  Go ahead and merge.

**Pull request merged**
