### PR TITLE
FIREFLY-1364 more updates and cleanup

### PR DESCRIPTION
**Pull request by wmiipac**
UI-conversion [FIREFLY-1364](https://jira.ipac.caltech.edu/browse/FIREFLY-1364).
Updated following popup dialogs:
- FitsDownloadDialog.jsx
- TableSave.jsx
- DownloadOptionsDialog.jsx
- PlotlySaveDialog.jsx

There are more cleanups needed in the DownloadOptionsDialog related to workspaces, which will be done in Firefly-1400.
To test: https://fireflydev.ipac.caltech.edu/firefly-1364/firefly/
1. do  a image search with wise and make 3 color image, and go to download image/3-color image
2. try a catalog search and in the table panel click save table

p.s `ZoomOptionsPopup` has been refactored already

#### Addresses: https://confluence.ipac.caltech.edu/display/IRSA/Testing+Feb+2024+-+Joy+UI%2C+mostly

Check when confirmed
- [ ] 20
- [ ] 46

### CODE REVIEW

**Review by robyww — CHANGES_REQUESTED** [review]
I looks like it is coming along well. The code looks good. However there are several little things and some layout issues.

Layout issues.

 - dialog width on TableSave.jsx line 81 should be a non-pixel value such as `32rem`
 - Probably something similar for FitsDownloadDialog.jsx
 - Image save: buttons should be on bottom
 - Save table: the bottom buttons some margin at the below
 - Save table, File format: put the label on top (`orientation='vertical'`)
 - Save Chart: make the dialog a little wider, like `25rem`
 - question mark should be on far left
 - remove the colon on all filename labels since it is the label is on top and not the side
 use approach
```
<Stack justifyContent = space-between>
    <Stack spacing=1>
           button
           button
    </Stack>
    HelpIcon
<Stack>
```

**Comment by wmiipac** [comment]
@robyww  made a new dev build with most of the changes and converted the chart save dialog. please check again:
[FIREFLY-1364-update-dialogs](https://fireflydev.ipac.caltech.edu/firefly-1364/firefly/)

p.s. I did not convert the labelWidth to rem, the ListBoxInputField is expecting a number propType.

**Review by robyww — APPROVED** [review]
Looks good! 

Thanks.

**Comment by lrebull** [comment]
#20: I'm not sure this is complete. On ops, there are three things: 
- Type of files
- File name
- File location
On this build, there are only two -- the "File location" is missing. Is that intentional? Are we downgrading the "workspace" option at all?
Also, I know this is a change with respect to ops, but as I mentioned on the big confluence page, it really should be "Type of file" and not "Type of files".

#46: this looks a lot better, but there's the same thing with regards to the lack of "workspace" as a choice. Is this an intentional removal?

**Comment by robyww** [comment]
@lrebull this is a firefly build. You don't see workspace in it

**Comment by lrebull** [comment]
ah, ok

**Comment by lrebull** [comment]
so the only thing lingering is "type of file"

**Comment by wmiipac** [comment]
@lrebull I will address the type of file in another ticket (Firefly-1400) when I convert the workspace panel.

**Pull request merged**
