### PR TITLE
FIREFLY-1445: adjust cleanup script to keep upload files for 1 day

### PR DESCRIPTION
**Pull request by loitly**
https://jira.ipac.caltech.edu/browse/FIREFLY-1445

Moved 'upload' to policy-managed directories with a set time of 1 day from last access. 
Also, use access time for the configurable directories rather than modification date.

Test: https://firefly-1445-upload-cleanup-tweak.irsakudev.ipac.caltech.edu/irsaviewer/

Instead of having @lrebull test this, I suggest we merge after a code review.  This is a minor adjustment and should not cause any undesirable operational issues.  She can submit new tickets if the problems persist.

### CODE REVIEW

**Comment by lrebull** [comment]
sounds good -- i'm the one most likely to stumble across ongoing problems with this as i continue to update the docs, translate them into docs for the other tools, make movies, and (occasionally) do science ... :)

**Comment by robyww** [comment]
One more thing... I thought you were going to try to make the message more clear?

**Comment by loitly** [comment]
You are right, I forgot about the error message.  I'll look into that.  
As for the duration, if you don't like 1d, then I will make it 7d like 'stage'.  I don't want to introduce a new value.

**Comment by loitly** [comment]
Test instance updated.  https://firefly-1445-upload-cleanup-tweak.irsakudev.ipac.caltech.edu/irsaviewer/
Here are a couple of error messages for you to look at.  These are not easily duplicate.
You can also cause exception by entering bad expression while adding columns and in 'Advanced Filter'.

image
image

**Comment by lrebull** [comment]
the first one is fine! the second one, i'd tweak slightly to be any one of these:

- IRSA search failed. Catalog is unavailable: Search...
- IRSA search failed; catalog is unavailable: Search ...
- IRSA search failed -- catalog is unavailable: Search ...

(focus on the connections between 'failed' and 'catalog')

**Pull request merged**
