### PR TITLE
DM-6239:fixed the label's issue when the coordinate is Ecliptic

### PR DESCRIPTION
**Pull request by lznakano**
Xiuqin,

Please check a few maps and let me know if  you spot any issues. 

Thanks!

### CODE REVIEW

**Comment by xiuqin** [comment]
I got two images side by side,  one 2MASS, one WISE.

1. The new version has doubled the lines of grid for WISE image (I used  m31 4band level1 image) not necessarily. 

2. for WISE image mentioned above, the equatorial (all 4 of them) coordinates display are out of the view on my monitor

3. Rotate north on WISE image, the labels disappeared.

4. I tried DSS image, the labels are out of view too.

**Comment by lznakano** [comment]
1. It does not make any sense since nothing has changed on  that respect.  
2-4. Also does not make sense to me.  The new values in most cases are  the same as the previous ones.  

Let me compare side by side using the exact data as you used.

**Comment by lznakano** [comment]
Hi Xiuqin,


What you noticed may be bugs either introduced by conversion or existed 
before.  The bug fixed in this branch is the labels only. To 
demonstrated what it is, I attached a screen shot.  On the old one is 
(GWT) irsa/irsaviwer and the new one is on the left side (localhost....)

You can see that the labels in the GWT version are not placed right.  
But the new one is fine.  This is all about this ticket.

Great, you did more tests.  I  did some tests but always use the images 
I know.  It could be more bugs.  Please submit tickets for everything 
you found.  THANKS!



On 6/8/16 12:35 PM, Xiuqin Wu wrote:
>
> I got two images side by side, one 2MASS, one WISE.
>
> 1.
>
>     The new version has doubled the lines of grid for WISE image (I
>     used m31 4band level1 image) not necessarily.
>
> 2.
>
>     for WISE image mentioned above, the equatorial (all 4 of them)
>     coordinates display are out of the view on my monitor
>
> 3.
>
>     Rotate north on WISE image, the labels disappeared.
>
> 4.
>
>     I tried DSS image, the labels are out of view too.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/Caltech-IPAC/firefly/pull/100#issuecomment-224703153>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/ALbTfRdkWrcn4EZUq0bKPGEYZJBHBYWaks5qJxmKgaJpZM4IxRCB>.
>

-- 
Lijun Zhang

LSST/IPAC
California Institute of Technology
770 S. Wilson Ave, Mail Code 100-22
Pasadena, CA 91125, USA
Voice: 1-626-395-1972 Fax:1-626-395-1816

**Comment by xiuqin** [comment]
Please change the content of the same ticket and fix the bugs.

**Comment by lznakano** [comment]
Xiuqin,


You have to show me the issues you saw.  I can not reproduce them.  I 
have both the GWT and JS version side by side.  They both work the same 
except the bug I just fixed.

I tried wise m31 as what you described.

I need to leave today.  I will check with you tomorrow morning. If 
something is not right, it could be there before.



Lijun

On 6/8/16 3:38 PM, Xiuqin Wu wrote:
>
> Please change the content of the same ticket and fix the bugs.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/Caltech-IPAC/firefly/pull/100#issuecomment-224752126>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/ALbTfVjhuPBi05q5GQhrCWyA-ndjW4Rvks5qJ0RugaJpZM4IxRCB>.
>

-- 
Lijun Zhang

LSST/IPAC
California Institute of Technology
770 S. Wilson Ave, Mail Code 100-22
Pasadena, CA 91125, USA
Voice: 1-626-395-1972 Fax:1-626-395-1816

**Pull request merged**
