### PR TITLE
Firefly-950,Firelfy-139,IRSA-3170: bug fixes

### PR DESCRIPTION
**Pull request by robyww**
### Bug Fixes
   - [Firefly-950](https://jira.ipac.caltech.edu/browse/FIREFLY-950): restore TimeSeries download button
   - [Firelfy-139](https://jira.ipac.caltech.edu/browse/FIREFLY-139): fixed color panel showing invalid state when valid
   - [IRSA-3170](https://jira.ipac.caltech.edu/browse/IRSA-3170): fixed

### Testing

 - Firefly-139:
    - https://fireflydev.ipac.caltech.edu/firefly-950-139/firefly/ts.html
    - load any time series, The download button will be there.
 - Firefly-950:
    - https://fireflydev.ipac.caltech.edu/firefly-950-139/firefly/
    - load any image
    - bring up color dialog
    - enter and invalid percent then switch to data
- IRSA-3170:
    -  https://fireflydev.ipac.caltech.edu/firefly-950-139/firefly/ts.html
    - start a download and then cancel, or send to background, or let it finish
    - in call three cases the download dialog should close

### CODE REVIEW

**Review by ejoliet — APPROVED** [review]
yeah! button is back. I tested and download works. 
Only related thing remaining to do if it's an easy fix is the agreed task here IRSA-3170 => "When a user clicks "Prepare Download", the dialog should close."

Thanks!

**Comment by robyww** [comment]
I will implement IRSA-3170

**Comment by lrebull** [comment]
I confirm "prepare download" button is back (FIREFLY-950) and seems to actually prepare the download. :)
Following the stuff spelled out in the description of FIREFLY-139, I get the same error/behavior as described there, so I think that is not fixed.
I confirm that the download dialog seems to disappear as requested in IRSA-3170, though initially I was getting strange behavior where I couldn't cancel it or send it to the background. Now, I can't reproduce that behavior. I'm assuming it was hotel WiFi weirdness but will also watch for it in the next build I test when back in the office with "real" internet. :)

**Comment by lrebull** [comment]
Noting this here as well as in IRSA-3170 for reasons that will become apparent. 

Testing this ticket before: started a download. Clicked on "send to background." nothing happened. Clicked on "cancel." Nothing happened. Wait. Wait. Wait. Tried again. Inadvertently highlighted text. Nothing happens, nothing seems to be happening. Kill browser tab. Try again. Now all works flawlessly.

The reason I mention this here? Trying to test https://github.com/Caltech-IPAC/firefly/pull/1196. Trying to get a catalog to come up so that I can test saving it to make sure I still can without the pop-up kludge we implmented for ops. Have now encountered the same behavior I did on this build earlier: Clicked on "send to background." nothing happened. Clicked on "cancel." Nothing happened. Wait. Wait. Wait. Tried again. Inadvertently highlighted text. Nothing happens, nothing seems to be happening. Kill browser tab. Try again. Now all works flawlessly.

**Review by ejoliet — COMMENTED** [review]
Looks good! Thank you!!

**Comment by robyww** [comment]
@lrebull [Firelfy-139](https://jira.ipac.caltech.edu/browse/FIREFLY-139) seems fixed to me. Maybe you are doing something I have not tested. I have tested it according to the ticket and it appears fixed.

I think you are traveling today. I think I will merge the PR and if you are still finding an issue next week I will do a further fix then.

**Pull request merged**
