### PR TITLE
Firefly-1276,Firefly-1277

### PR DESCRIPTION
**Pull request by robyww**
#### [Firefly-1276](https://jira.ipac.caltech.edu/browse/FIREFLY-1276),[Firefly-1277](https://jira.ipac.caltech.edu/browse/FIREFLY-1277)

- fixed: Overlapping fields in readout display area
- fixed: Mask overlay on incompatible images
- fix client side data analyzer table loading

#### Testing
- https://fireflydev.ipac.caltech.edu/firefly-1276-readout/firefly
- test according to tickets

### CODE REVIEW

**Comment by tgoldina** [comment]
The mask overlay is fixed. The overlapping pixel readout is not. It is still overlapping with larger Flux numbers. (I tested both with the image attached to FIREFLY-1277 (img_flg_psf_wl.fits) 

Screen Shot 2023-07-13 at 9 57 09 AM

"Lock by Click" checkbox keeps jumping, when the mouse is entering active area.

**Comment by robyww** [comment]
new build fixes the above issue..

**Comment by tgoldina** [comment]
Just curious why the spatial coordinates always have the three dot ellipsis. The ellipsis after flux value only shows if the space is very tight.

Screen Shot 2023-07-14 at 12 34 53 PM

**Review by tgoldina — COMMENTED** [review]
Thank you very much for the fix.

**Review by tgoldina — APPROVED** [review]

**Pull request merged**
