### PR TITLE
Firefly 1420 cleanup items

### PR DESCRIPTION
**Pull request by loitly**
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-1420

Converted DialogRootContainer.DropDown to JoyUI Dropdown.
Converted `View As Text`  popup
Added Stacker container

Also worked on issues from: https://confluence.ipac.caltech.edu/pages/viewpage.action?pageId=674536199
- [ ] 4: Too much padding in table Headers
- [x] 13:Image Search: move expand icon next to dataset label
- [x] 21: size of the save table pop-up is not big enough 
- [x] 22: revert to checkboxes
- [x] 23: use old add column icon.  does not support dark mode

Test: https://fireflydev.ipac.caltech.edu/firefly-1420-cleanup-items/firefly

### CODE REVIEW

**Comment by lrebull** [comment]
Ok, i'm trying ... 
item 4 talks about table headers/widths. the example given is in DCE. the build above is just firefly. Ok, fine; i went to ops and got a table from DCE (attached), and tried to upload it to the firefly build above. I get:
Table Load Error:
java.lang.RuntimeException: Type mismatch(false): expecting class java.lang.Boolean but found class java.lang.String

help?

[table_IRIS-Images-1.tbl.gz](https://github.com/Caltech-IPAC/firefly/files/14438120/table_IRIS-Images-1.tbl.gz)

**Comment by lrebull** [comment]
#21 is fixed!
#22 is fixed!
#23 is using old icon and i think it looks ok in dark mode..?

**Comment by lrebull** [comment]
At Trey's suggestion, tried a TAP search in this build. Now some of the headers are way too narrow. See screenshot.
Screenshot 2024-02-28 at 9 49 23 AM

**Comment by loitly** [comment]
@lrebull @robyww, IRSA TAP is a bad choice for testing #4.  IRSA returns table with attribute ` width="5"` in their FIELDs.  Firefly will use that value to set the default width when given.  You can see this in OPS as well.

**Pull request merged**
