### PR TITLE
FIREFLY-1422-ui-rubin-irsa: Multiple fixes from IRSA and Rubin testing

### PR DESCRIPTION
**Pull request by robyww**
#### [FIREFLY-1422-ui-rubin-irsa](https://jira.ipac.caltech.edu/browse/FIREFLY-1422): Multiple fixes 

- Irsa testing round 2: 8, 30, 45
 - Rubin - Landing page: 2,4,5,7,8,9,10,11,12 - Table Component: 1

#### Testing
- https://firefly-1422-ui-rubin-irsa.irsakudev.ipac.caltech.edu/irsaviewer/

#### issues

IRSA testing round 2
https://confluence.ipac.caltech.edu/pages/viewpage.action?pageId=674536199

- [x] 8
- [x] 30
- [x] 45

Rubin Landing page, etc
https://confluence.lsstcorp.org/pages/viewpage.action?pageId=250480825

- [x] 2
- [x] 4
- [x] 5
- [x] 7
- [x] 8
- [x] 9
- [x] 10
- [x] 11
- [x] 12
- [x] Table component: 1

### CODE REVIEW

**Comment by lrebull** [comment]
irsa list:
- 8 is not fixed for me
- 30 doesn't seem to be fixed - it doesn't say "search position"
- 45 is fixed!

rubin list, landing page:
- 2 says "mouseover text to the tabs" (and in the side menu) and that Gregory will provide the text. I can't find any mouseover text specifics either in the request or in the build. The only thing I see that is new is that the Results tab now tells you how many images/tables you have in a mouseover, which is really nice, but doesn't seem to address the request.
- 4 says to put the line back at the top and has specifics on placement. That part is done, but the text has a typo: "ect)" --> "etc.)" (note letter swap and period at end)
- 5 says to keep the TAP service name in the upper left, and this is done!
- 7&8 are done here, but i gather from Slack that this is maybe still under discussion?
- 9 talks about alignment in the side menu, and is done!
- 10 alignment of 'hide' - seems fixed to me
- 11 upload icon in main tab (i noticed this right away when i loaded the build and i thought this was a great addition!)
- 12 - reset tab visibility - seems in right position and to work for me!

rubin list, tables # 1 - seems fixed to me!

**Comment by robyww** [comment]
@lrebull I should have specified more for rubin #2: I just provided the capability to have  a tooltip, it is demonstrated in Upload

**Comment by lrebull** [comment]
irsa 8 now works properly for me!
I'm still not sure about irsa 30, because it still doesn't say "search position" but it may be that we need to defer that discussion (again)

**Comment by lrebull** [comment]
(Rubin 4 is done now too)

**Pull request merged**
