### PR TITLE
FIREFLY-1550: Save table in Parquet format

### PR DESCRIPTION
**Pull request by loitly**
Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-1550

Add support for saving a Firefly table in Parquet format. 
The file will be saved as a `parquet.votable` file, which is a Parquet file with  VOTable metadata. This will allow users to store table data in a highly efficient, columnar storage format while preserving the rich metadata associated with VOTables.

More details about the standard here: https://github.com/astropy/astropy/pull/16375
Sample files here: https://vizcat.cds.unistra.fr/hats:n=1000000/

While testing, I noticed Firefly fails to write out RESOURCES when they are present.  I file this as a bug [FIREFLY-1563](https://jira.ipac.caltech.edu/browse/FIREFLY-1563)

Also, I noticed many sample files with `unit=[]`.  Is this something Firefly need to interpret as empty string or null?

Test: https://fireflydev.ipac.caltech.edu/firefly-1550-save-parquet/firefly/
- Upload or query table data
- Save the table in Parquet format
- Upload the saved Parquet file to demonstrate a round-trip process

### CODE REVIEW

**Review by robyww — APPROVED** [review]
Looks good!

**Comment by mbtaylor** [comment]
Hi @loitly and other interested parties.  I'm assessing the proposal at [astropy/astropy#16375](https://github.com/astropy/astropy/pull/16375) for possible formalisation as a (IVOA?) standard, on the grounds that it would be better to have this convention written down somewhere findable than defined ad hoc by a PR and implementation code.

To help with that, could you make available one of the example output files that firefly outputs in this format? The referenced test directory at https://fireflydev.ipac.caltech.edu/firefly-1550-save-parquet/firefly/ is not accessible to me.

Please let me know if you're interested in the standardisation discussions as well.

Thanks.

**Comment by loitly** [comment]
@mbtaylor Here’s an example of the original VOTable from IRSA TAP, along with the converted file after Firefly saved it as Parquet.  
[allwise_p3as_psd.zip](https://github.com/user-attachments/files/17441041/allwise_p3as_psd.zip)

**Comment by mbtaylor** [comment]
Thank you - it looks good.

**Pull request merged**
