### PR TITLE
Firefly-1208: Multi ticket

### PR DESCRIPTION
**Pull request by robyww**
#### Multiple Tickets

- [x] [Firefly-1208](https://jira.ipac.caltech.edu/browse/FIREFLY-1208): switch between coordindates
- [x] [Firefly-1200](https://jira.ipac.caltech.edu/browse/FIREFLY-1200): don't add MOC to coverage
- [x] [Firefly-1210](https://jira.ipac.caltech.edu/browse/FIREFLY-1210): Results HiPS on coverage map should be same as search HiPS
 - [x] [Firefly-1206](https://jira.ipac.caltech.edu/browse/FIREFLY-1206): DCE: blocked from picking polygon
 - [x] [Firefly-1204](https://jira.ipac.caltech.edu/browse/FIREFLY-1204): tooltip and label changes
 - [x] [Firefly-1205](https://jira.ipac.caltech.edu/browse/FIREFLY-1205): table filter buttons together
 - [x] [IRSA-5190](https://jira.ipac.caltech.edu/browse/IRSA-5190)

#### Testing
 - https://firefly-1208-projection.irsakudev.ipac.caltech.edu/irsaviewer/dce

### CODE REVIEW

**Comment by lrebull** [comment]
ticket 1208: hm. some of them are doing what i thought they would, and some are not... let me see if i can do a systematic list.

1200- looks great!

1210 - also looks great, is doing what i expect it to do, even when i search on a second completely different data set.

1206 - works great

1204 - #1 is almost there. "Show Other Data collections" --> "Show Other Data Collections" for internal consistency
the others. The other requests in that ticket are unchanged as far as I can tell.

**Comment by lrebull** [comment]
I put a movie in firefly-1208 to try to explain (i sorted myself out on one of the things)

**Comment by lrebull** [comment]
1205 is working great!

**Comment by robyww** [comment]
@lrebull 

- [ ] based on our discussion yesterday and my comments on the ticket. I think firefly-1208 is working.
- [ ] I added the missing to firefly-1204

**Pull request merged**
