### PR TITLE
IRSA-4793: allow to use band for more than one color

### PR DESCRIPTION
**Pull request by robyww**
#### [IRSA-4793](https://jira.ipac.caltech.edu/browse/IRSA-4793): allow to use band for more than one color
- user may now use a color band for more than one observation bands

#### Testing
- https://irsa-4807-three-color.irsakudev.ipac.caltech.edu/applications/wise/
- use 3 color setting the same color band to more than one wise band

### CODE REVIEW

**Comment by lrebull** [comment]
After you create a 3-color image, you cannot update it.

**Comment by lrebull** [comment]
(you have to remove it and recreate it to change it)

**Comment by robyww** [comment]
I don't understand, I have changed it several times. I guess I need more details.

**Comment by lrebull** [comment]
ARGH it failed until i tried to make a movie for you and now of course it's working flawlessly.... i will not share with you the movie of it working flawlessly because of course it's working flawlessly... gah.....

**Review by wmiipac — APPROVED** [review]
Works great. The "Duplicate bands" warning looks good. 
We should documented in the help the difference of “disable” a band and reuse a band in creating the color image.

**Pull request merged**
