### PR TITLE
Firefly Multi ticket: fix multiple issues

### PR DESCRIPTION
**Pull request by robyww**
####  Firefly Multi ticket: fix multiple issues

- [x] [Firefly-1201](https://jira.ipac.caltech.edu/browse/FIREFLY-1201): drawing layers disappearing when you clicks on new search target
- [x] [Firefly-1203](https://jira.ipac.caltech.edu/browse/FIREFLY-1203): fixed: mouse readout title not changing
- [x] [Firefly-1199](https://jira.ipac.caltech.edu/browse/FIREFLY-1199): search target zoom to fit
- [x] fixed issue requesting data too many times, create a 'Load Image Rendering' error

#### Testing

- https://firefly-multi-draw-layers.irsakudev.ipac.caltech.edu/irsaviewer/dce

### CODE REVIEW

**Comment by lrebull** [comment]
confirm 1201 is fixed

**Comment by lrebull** [comment]
now i can't make the pop-up for the coordinates go away... stand by for a movie ...

**Comment by lrebull** [comment]
https://user-images.githubusercontent.com/23038600/230206381-bf98fd25-8faf-42d0-8e07-02dd00114040.mp4

**Comment by robyww** [comment]
@lrebull fixed the dialog closing issues and added Firefly-1199 to the PR

**Comment by lrebull** [comment]
I saw the slack git message, so i already checked the pop-up closing! :) that works!

but i didn't notice the addition of the new ticket. checking that.

**Comment by lrebull** [comment]
ooh, much better on 1199!

**Pull request merged**
