### PR TITLE
DM-8566: build related fixes

### PR DESCRIPTION
**Pull request by loitly**
https://jira.lsstcorp.org/browse/DM-8566

 - Fix duplicate nom.tam.fits classes during build
 - Add preferIPv4Stack to tomcat env.
 - Add firefly.war to Firefly Standalone release page

Temporarily added this branch to jenkin's build to test the Firefly Standalone fix.
preferIPv4Stack=true is added to setenv.sh in ife-env repo

### CODE REVIEW

**Comment by tgoldina** [comment]
The changes seem to be right, but I am not sure how to test them. Should we merge it and then I merge dev into master and build standalone?

**Comment by loitly** [comment]
This branch was added as a choice for Jenkins standalone build. You can test it without merging.

**Comment by loitly** [comment]
Added Development and Main task groups into gradle print out.  When running 'gradle tasks', it will appear last.

**Comment by tgoldina** [comment]
Approved.

**Pull request merged**
