### PR TITLE
Firefly 1215: Improved TAP UI 

### PR DESCRIPTION
**Pull request by robyww**
#### [Firefly-1215](https://jira.ipac.caltech.edu/browse/FIREFLY-1215): TAP Panel UI improvements

 - new look with services and ADQL controls
 - allows for service specific label for schema 
 - various small layout improvements

#### Testing

- https://fireflydev.ipac.caltech.edu/firefly-1215-tap-concept/firefly/
- play with the TAP panel

### CODE REVIEW

**Comment by lrebull** [comment]
I think it looks nice! 
absolutely the only thing i'd change is in the multiposition search - change to "from the uploaded table" (see screen shot)
Screen Shot 2023-04-12 at 4 14 36 PM

**Review by loitly — COMMENTED** [review]
I liked it much better than before.  A lot less jumpy.  Good work.

**Review by kpuriIpac — COMMENTED** [review]
Looks great! 
Question: are the Show/Hide buttons meant to do both? for example, I can click on just "Show" to show the TAP service, and then click on "Show" again to hide it. Same goes for the "Hide" button. I don't think this was the case in the previous iteration, so just wanted to check if it's desired behavior.

**Comment by robyww** [comment]
@kpuriIpac 
> then click on "Show" again to hide it. 

No thats a bug. I will fix it. thanks

**Comment by lrebull** [comment]
@robyww 
> @kpuriIpac
> 
> > then click on "Show" again to hide it.
> 
> No thats a bug. I will fix it. thanks

Interesting! I thought it was deliberate!!

**Pull request merged**
