### PR TITLE
IRSA-4226: Finder Chart batch(multi positions) searches fail

### PR DESCRIPTION
**Pull request by loitly**
Ticket: https://jira.ipac.caltech.edu/browse/IRSA-4226
Test   : https://irsa-4226-finderchart-multipos-fail.irsakudev.ipac.caltech.edu/applications/finderchart/

Fixes a bug where a string is requested to be formatted as a decimal number.
Follow ticket's description for testing.

### CODE REVIEW

**Comment by lrebull** [comment]
Seems to be working better in that I get more than a grey screen! but no catalogs are loading for a batch search; all I get is "Table Load Error: Catalog Query Failed - network Error". It is a legit tbl file (sometimes when I get that error, that's the problem) because I just downloaded it from Gator on ops. Attaching a tbl file with the extension changed to txt to make github accept it.
[WISE-allwise_p3as_psd-Polygon.tbl.txt](https://github.com/Caltech-IPAC/firefly/files/7146670/WISE-allwise_p3as_psd-Polygon.tbl.txt)

**Review by robyww — APPROVED** [review]
Looks good.

**Comment by loitly** [comment]
> Seems to be working better in that I get more than a grey screen! but no catalogs are loading for a batch search; all I get is "Table Load Error: Catalog Query Failed - network Error". It is a legit tbl file (sometimes when I get that error, that's the problem) because I just downloaded it from Gator on ops. Attaching a tbl file with the extension changed to txt to make github accept it.
> [WISE-allwise_p3as_psd-Polygon.tbl.txt](https://github.com/Caltech-IPAC/firefly/files/7146670/WISE-allwise_p3as_psd-Polygon.tbl.txt)

I see the same problem in OPS.  I am wondering if there's a change in Gator's API.  I'll keep looking.

**Comment by loitly** [comment]
> I see the same problem in OPS. I am wondering if there's a change in Gator's API. I'll keep looking.

I asked Angela.  It's most likely a recent change to Gator API that created this problem.  The question was posted to #irsa 
 slack channel if you want to see more details.

**Pull request merged**
