### PR TITLE
Firefly-390,Firefly-391: Multiple coverage issues fixed.

### PR DESCRIPTION
**Pull request by robyww**
- Coverage: When doing coverage, then switching FITS or HiPS, and the FOV is 15 degrees or greater then it will attempt to center on the active row of the active table.
 - Coverage: When 'pan by table row' is on, the coverage is a FITS image not showing the whole table, and another row is clicked and if the row is off the image a new image will be loaded.
 - Zooming in auto mode, conversion will continue to center on the center of the zoom
 - fixed bug: when moving between an all sky FITS and HiPS. Failed to render.
 - fixed bug: with footprints, it did not catch coordinate conversion errors
 - the recenter button, when image is off the screen, now always recenters on image and not target
 - allow toolbar options to include the 'Pan by table row' button to be turned off
 - added `imageScrollsToActiveTableOnLoadOrSelect` app options, finderchart will set it false

https://jira.ipac.caltech.edu/browse/FIREFLY-391
https://jira.ipac.caltech.edu/browse/FIREFLY-390

### To Test Firefly Viewer
https://irsawebdev9.ipac.caltech.edu/firefly-390-table-pan/firefly/

#### Tests 1
1. Load multiple catalogs targets
    - using catalog, load two or three targets target (like  m1, m11, m31)
    - or use @lrebull upload file  https://jira.ipac.caltech.edu/secure/attachment/50510/example2input.tbl
1. switch to FITS. 
1. The FITS should be center on the active row
1. As you click around on the rows, new images will load

#### Test 2
1. Load multiple catalogs like above
1. You should see a AITOFF image, switch to HiPS
1. The HiPS should be centered on the active row.

#### Test 3
1. Load multiple catalogs like above
1. To really test will you should ready the ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-390

### To Test Finder Chart
 https://irsawebdev9.ipac.caltech.edu/firefly-390-table-pan/applications/finderchart/
1. use @lrebull upload file  https://jira.ipac.caltech.edu/secure/attachment/50510/example2input.tbl
2. Images will no longer jump out of frame when you switch tabs

### To Test Sofia
https://irsawebdev9.ipac.caltech.edu/firefly-390-table-pan/applications/sofia/
1. load and all sky search
2. I can't really describe the test.  You should read the ticket.
https://jira.ipac.caltech.edu/browse/FIREFLY-391
3. I think the coverage will now work _mostly_ as expected.

### CODE REVIEW

**Comment by ejoliet** [comment]
I tested all but SOFIA because it seems that the kubermetes POD is not working currently
https://irsawebdev9.ipac.caltech.edu/firefly-390-table-pan/applications/sofia/

The rest of my tests were all good.

**Comment by lrebull** [comment]
I'm sorry, maybe I'm just being excruciatingly dense, but I don't understand. The link that you said to test was https://irsawebdev9.ipac.caltech.edu/firefly-390-table-pan/firefly/, right? This is just an IRSA Viewer incarnation (with lots of additional options I've not seen before), but I can't use it to duplicate the SOFIA problem, the Finder Chart problem, or the Gator problem, because it's not able to take a batch list of targets. What horrifically obvious thing am I missing? When I try to replicate some of what you described, I get the same behavior as earlier. This is what I thought you were telling me to try:
Load into https://irsawebdev9.ipac.caltech.edu/firefly-390-table-pan/firefly images of one target (I picked M16, all 5 SEIP bands)
Then load on top of it images of another target (I picked M1, again all 5 SEIP bands). 
Then load a catalog (I used my example tbl). 
It says in your description: "When 'pan by table row' is on, the coverage is a FITS image not showing the whole table, and another row is clicked and if the row is off the image a new image will be loaded."  I do not get a coverage image. I do not get a new image if the row is off the image. 

I'm super confused, and I do apologize, but I don't get it... Am I already supposed to be looking at irsadev?

**Comment by robyww** [comment]
@luisa.

-  My description above has 3 URL’s. Just scroll down to find finder chart and SOFIA. 
- the image auto loading is when you load your multi target search from the catalog panel like you did. Then on the coverage tab you change to FITS. Then click on various rows.

**Comment by lrebull** [comment]
AH! the email that github sent does NOT have multiple links. but the information in the actual ticket does. That was my problem.

**Comment by lrebull** [comment]
(AH! the email that github sent does NOT have multiple links. but the information in the actual ticket does. That was my problem.)

opening the SOFIA one nets me a 404 not found, so I still can't test that.

Finder Chart is much better! That's clearly fixed.

Loading a catalog into this incarnation https://irsawebdev9.ipac.caltech.edu/firefly-390-table-pan/firefly/ before loading any images at all at least tries to generate a coverage map, but I get "Failed: Could not create plot" instead of a coverage image.

So I still can't test 2 of the 3.  And, I still can't test Gator (that was one of the original ticket issues).

**Comment by robyww** [comment]
@lrebull  I think we were having some test server problems.

> opening the SOFIA one nets me a 404 not found, so I still can't test that.

Working now. https://irsawebdev9.ipac.caltech.edu/firefly-390-table-pan/applications/sofia/

> but I get "Failed: Could not create plot" instead of a coverage image.

I just tried your upload file in the viewer and it is working as well.
https://irsawebdev9.ipac.caltech.edu/firefly-390-table-pan/firefly/

**Comment by lrebull** [comment]
Yes, I agree it's working now!
FinderChart (still) ok
IRSA Viewer with a catalog loaded first so as to force it to make a coverage image now also works.
I'm still having problems with SOFIA. I'll make a movie and put it in the ticket (not here).

**Pull request merged**
