### PR TITLE
FIREFLY-1396: Display TAP overflow indicator when present in VOTable

### PR DESCRIPTION
**Pull request by loitly**
The INFO tags inside the RESOURCE were not populated, which is why the overflowed TAP results were not marked. This was an oversight on my part. Please test again.

https://fireflydev.ipac.caltech.edu/firefly-1396-votable-overflow/firefly/

### CODE REVIEW

**Review by gpdf — CHANGES_REQUESTED** [review]
Functionally this looks like it works now for IRSA TAP.

I would still like to see the feature from the FIREFLY-556 mock-up where, in the table-info dialog, the words "Results truncated" appear after the warning triangle.  See https://github.com/Caltech-IPAC/firefly/pull/1540#discussion_r1568031617 for an inline comment on the previous PR at the point where I think this would apply.

I've tested this with a manually uploaded VOTable from the Rubin TAP service as well and verified that the "OK followed by OVERFLOW" style of that VOTable also works.  However, I noticed that the overflow is not reported in the Table Info "(i)" dialog for a manually uploaded table.  That wasn't covered by the original ticket, of course, but it seems odd from a user perspective to have it show up in the top material of the table but not in "table info".

The appearance of the "Table Info" dialog for a manually uploaded table is also odd:

image

It looks blank even though the "Table Metadata" tab is active and has content.  If there's only one tab, shouldn't it always be active?

**Comment by loitly** [comment]
> "Results truncated"

Sorry.  Overlooked.  It's added now.  Please test.

> The appearance of the "Table Info" dialog

I can't reproduce.

**Comment by gpdf** [comment]
Confirmed that "Results truncated" appears now.  I think it would be better if the mouseover applied both to those words and to the warning-triangle icon, if that change is easy to make.

Confirmed that added columns now have their distinctive colors again.

Also cannot reproduce the odd behavior of the Table Info dialog.  I'll keep an eye out for this in the future.

I still think that it would be good for the overflow to be reflected somehow in the Table Info dialog, for uploaded tables with overflows, but since this is a rare situation, I'm not asking for this to be changed on this PR.

**Review by gpdf — APPROVED** [review]
Approved; if modifying the mouseover scope as mentioned in my comment above is fast, please do that, otherwise this is good to go.

**Pull request merged**
