### PR TITLE
IRSA-2157-IRSA Viewer: Add the rest of the Spitzer datasets in image search & results

### PR DESCRIPTION
**Pull request by lznakano**
Add spitzer dataset listed in the ticket.

NOTE:
Among the list there are two of which do not have IBE table information.  8 of 29 dataset failed at image search.  The failed datasets are:
1. GOALS
2. GOODS
3. FIDEL
4. IUDF
5. SAGE and SAGE-Spec
6. SDWFS  (NO IBE table)
7. SMUVS  (NO IBE table)
8. SSDF
9. S_cosmos
10. Abell

### CODE REVIEW

**Comment by lznakano** [comment]
Good catch!!  Fixed, please check it again!!!  Thanks!

**Comment by ejoliet** [comment]
Another issue is on row 84:
`

Spitzer | Cygnus-X: A Spitzer Legacy Survey of the   Cygnus-X Complex | Cygnus-X | spitzer.glimpse_cygx_0_6 | Gygnus-X | IRAC4 |   | IRAC   (8.0 microns) | 8 | 8 microns | galactic | galactic | 0.08 | 2 | https://irsa.ipac.caltech.edu/data/SPITZER/GLIMPSE/overview.html | Cygnus-X IRAC ch4 8 microns | ATLAS | file_type='science' | image
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Spitzer | A 24 and 70 Micron Survey of the Inner Galactic Disk with MIPS (MIPSGAL)   Data Collection Atlas | MIPSGAL | spitzer.mipsgal_images | MIPSGAL | MIPS24 |   | MIPS (24 microns) | 24 | 24 microns | MIPSGAL | galactic |   |   | http://irsa.ipac.caltech.edu/data/SPITZER/MIPSGAL/ | MIPSGAL MIPS 24 microns | ATLAS | file_type='science' and fname  NOT   like '%resid%' | image
`
The rows after are not correct. See column for `projectType`...

**Comment by lznakano** [comment]
Somehow, I don't get to see the issue on row 84.  But I deleted it and added it again.  Please have a look.  Thanks!

**Comment by ejoliet** [comment]
Will merge from my local.

**Pull request merged**
