### PR TITLE
irsa-3696:BOLOCAM labels

### PR DESCRIPTION
**Pull request by lznakano**
https://jira.ipac.caltech.edu/browse/IRSA-3696
  
This PR update thed master table to change the bolocam's information.

Test URL:
https://lijun.irsakudev.ipac.caltech.edu/irsaviewer/

### CODE REVIEW

**Review by ejoliet — COMMENTED** [review]
Looks good!
Actually there was minor changes request in another ticket (IRSA-3697) that we could bring in here and avoid another PR, and merge all in once.

I can do it if you want and let you know.

**Review by ejoliet — APPROVED** [review]
Ok, just did, i've added minor changes requested in IRSA-3697. 

All good to merge from my side

**Comment by lznakano** [comment]
Let me know the ticket number. I will do in this pr. Thank you!

Sent from my iPhone

On Sep 17, 2020, at 5:45 PM, Emmanuel Joliet <notifications@github.com> wrote:

﻿

@ejoliet commented on this pull request.

Looks good!
Actually there was minor changes request in another ticket (IRSA-3697) that we could bring in here and avoid another PR, and merge all in once.

I can do it if you want and let you know.

**Comment by ejoliet** [comment]
I just did and added one more ;-) 
This PR once merged will include 3 tickets. IRSA-3696, IRSA-3697 and IRSA-3685.
Good to go.

**Pull request merged**
