### PR TITLE
Firefly-1209: polygon examples

### PR DESCRIPTION
**Pull request by robyww**
#### [Firefly-1209](https://jira.ipac.caltech.edu/browse/FIREFLY-1209)

- Fixed: download original file and other cleanup
- Fixed: coordinate system changes for hips when the HiPS does not change
- Fixed recenter and 
- Added pin badge

#### Testing
- https://firefly-1209-examples.irsakudev.ipac.caltech.edu/irsaviewer/dce

### CODE REVIEW

**Comment by lrebull** [comment]
I'm not sure how to test "download original file and other cleanup" or "coordinate system changes for hips when the HiPS does not change".

recenter and pinned image badge works great!!

**Comment by robyww** [comment]
@lrebull my comments where not very clear because I add more stuff. The original PR was about the polygon examples being dynamic. Did you test that.

**Comment by lrebull** [comment]
Wow, yes, I see that too. I haven't tried systematically every data set. Do tou want to merge before I ask someone to do that?

**Comment by robyww** [comment]
yes, I will merge.

**Pull request merged**
