### PR TITLE
IRSA-748: Replace image search with new ImageSearchPanelV2

### PR DESCRIPTION
**Pull request by loitly**
https://caltech-ipac.atlassian.net/browse/IRSA-748

Also includes:
- https://caltech-ipac.atlassian.net/browse/IRSA-955
- https://caltech-ipac.atlassian.net/browse/IRSA-956
- fix TargetPanel resolution in API demo pages
- fix API showImage and showCoverage not setting the right viewer's option

Build firefly and irsaviewer on this branch
Anywhere image search/load is available, the new ImageSearchPanel will appears.
This includes API, Gator, and elsewhere in firefly.

When updating current image, then panel allow for only 1 image to be selected.
Otherwise, you can select more than one, and have them all loaded at once.

@cwang2016 , will you help check to see if any features missing in this new panel.
@robyww , will you do the same.  Also, you want to look over the small changes I made to image API.

### CODE REVIEW

**Comment by cwang2016** [comment]
please check if this is a bug, 
- select single channel image -> archive -> target: m31 -> SDSS -> u
   the image is shown as Failed - SDSS Area not covered. 
- back to image search panel, unckeck SDSS and check WISE (at this time SDSS/u seems still stored, but not seen) -> click search
result: no error message popped up to ask for selecting at least an image and the image is still shown as 'Failed - SDSS Area not covered. '
Q: should SDSS/u be unchecked before SDSS is unchecked?

**Comment by cwang2016** [comment]
Is this as design? 
'Archive' is the default selection for 'Single channel image' and 'None' is the default selection for 3-color red, green and blue?

**Comment by cwang2016** [comment]
Is this working as designed?  There is  no 'replace image' (vs. create new image)  from the image search?

**Comment by cwang2016** [comment]
A very minor question, do you want to add ':' to "Choose Radius'  like 'Name or Position: '.

**Comment by cwang2016** [comment]
This is regarding the image rendering, no title (only zoom number)  is shown at the left corner if the image is selected  from 'Upload' and image file.

**Comment by ejoliet** [comment]
> select single channel image -> archive -> target: m31 -> SDSS -> u
the image is shown as Failed - SDSS Area not covered.
Not bug, try m81 ;-)

**Comment by cwang2016** [comment]
This is regarding 
select single channel image -> archive -> target: m31 -> SDSS -> u

Sorry I didn't state clearly. I didn't mean ' Failed - SDSS Area not covered.' is a bug.  What I meant is when you go back to deselect 'SDSS' and then select WISE or others (without selecting an image), the search is still repeatedly done on SDSS since the same error message is displayed.

**Comment by robyww** [comment]
Initial Observations:

-  file upload and url should use the WebPlotRequest factory methods: `makeFilePlotRequest` and `makeURLPlotRequest`. This will fixed the title issues the @cwang2016 saw.
- Workspace should be added.
- When workspace is added it needs to check app options: `workspace.showOptions`
- We need to implement the sort order parameter in `ImageMasterData.java` and `GetMasterImageData` on the server side. This must be done we can't hard code  the order. 
- The client should specify the sort order in app options in the html file.  This allows IRSA and LSST to get the correct images on top.
- I still really think we need to clear the image options when the dialog is raise.  It is just too easy to bring up multiple copies of the same image.
- I think it would look a little less cramped it the `.ImageSearch__section` has `padding: 6px 2px 4px 2px`, `margin: 2px 4px 2px 4px`  and `width: calc(100% - 8px);`

**Comment by loitly** [comment]
> 'Archive' is the default selection for 'Single channel image' and 'None' is the default selection for 3-color red, green and blue?
This was my decision.  I wanted the user to purposely select which color they want to create.  If they choose just 1 or 2, they should not be prompt with validation errors, then needing to go back and deselect what they did not select in the first place.  If this is not desire, I have no problem changing it to whatever the desire behavior should be.  @ejoliet @robyww

**Comment by loitly** [comment]
> Is this working as designed? There is no 'replace image' (vs. create new image) from the image search?

Yes, it's default to add.  We will replace only when add is not allowed.

**Comment by loitly** [comment]
> select single channel image -> archive -> target: m31 -> SDSS -> u

This is normal, because we do not clear previous results.  Therefore, WISE was added to the previously results leading you to think that 2 images was added on your second try when in fact only WISE was added.

**Comment by ejoliet** [comment]
>file upload and url should use the WebPlotRequest factory methods: makeFilePlotRequest and makeURLPlotRequest. This will fixed the title issues the @cwang2016 saw.

Good!

>    Workspace should be added.    When workspace is added it needs to check app options: workspace.showOptions

Agree.
    
> We need to implement the sort order parameter in ImageMasterData.java and GetMasterImageData on the server side. This must be done we can't hard code the order.
The client should specify the sort order in app options in the html file. This allows IRSA and LSST to get the correct images on top.

I vote for postponing unless it can be done in this branch.

> I still really think we need to clear the image options when the dialog is raise. It is just too easy to bring up multiple copies of the same image.

Until we have a way to see what have been selected, i would suggest to keep the selected checkboxes, otherwise there is no other way currently to see what i've selected. Right?

**Comment by loitly** [comment]
In response to @ejoliet comment, I've already done most of the suggested changes in this PR.
I still need to add workspace and selected/filtered indicators.

So far, these are fixed:
-  file upload and url should use the WebPlotRequest factory methods: `makeFilePlotRequest` and `makeURLPlotRequest`. This will fixed the title issues the @cwang2016 saw.
- We need to implement the sort order parameter in `ImageMasterData.java` and `GetMasterImageData` on the server side. This must be done we can't hard code  the order. 
- The client should specify the sort order in app options in the html file.  This allows IRSA and LSST to get the correct images on top.
- I still really think we need to clear the image options when the dialog is raise.  It is just too easy to bring up multiple copies of the same image.
- I think it would look a little less cramped it the `.ImageSearch__section` has `padding: 6px 2px 4px 2px`, `margin: 2px 4px 2px 4px`  and `width: calc(100% - 8px);`
-A very minor question, do you want to add ':' to "Choose Radius' like 'Name or Position: '.

**Comment by loitly** [comment]
@cwang2016 @robyww @ejoliet 

I've pushed a new commit to deal with the above requests.
I still have `workspace` to do tomorrow.
But since we're on a tight schedule, if you can review the new UI elements to see if it's acceptable while I work on `workspace`.   It would be helpful.

Here are the things I added:
- use WebPlotRequest factory methods
- implement ImageMasterData sortOrder
- clear inputs and cosmetics changes
- add selected indicators in filter and selection panels
- added clear filters and clear selections

If you go to firefly-dev.html, you'll get the new sorted feature added using ['WISE', '2MASS', 'Spitzer'] as the sort param.

I, without thinking, rebase my branch with dev.  You'll have to remove your local branch to get my new changes.  Sorry.

**Comment by ejoliet** [comment]
Thanks. 
I'm happy to see the introduction of "clear selection". Selected indicators is a cool workaround! Like it! Nice idea!

I've tried to filter MSX, SDSS OR DSS but it fails with "No data match these criteria
".

I'm not sure that we still want to clear the selection of the form. It seems that now when i go back to the form, it also cleared the search target. I don't think is an improvement. but anyway, we don;t have time for that so ship it as it is, i'm sure others will have different opinion and this shouldn't stop from merging.

The idea of the order for IRSA (Archive) was that it was coming from the table otherwise Vandana can't control it with fine granularity but again, is fine for now. We will have to see how we adjust to it.

**Comment by robyww** [comment]
Starting to look at it... The three color does not seem  to work anymore.  When I click search it does not do anything.
So far everything else looks good.  I will keep testing.

**Comment by loitly** [comment]
Latest commit includes workspace option for Image Source.  This PR is complete and ready to merge once approve.
NOTE:
You need to edit `/hydra/server/tomcat/webapps/firefly/WEB-INF/config/app.prop` and set `ignore.auth=false` for workspace to work.

**Comment by cwang2016** [comment]
The latest commit works well. Here a small concern, workspace upload related. The title shown on the image is the filename at the server instead of the original filename from the workspace, not like what Fits file upload we did on local file system.

**Pull request merged**
