### PR TITLE
DM-7275: fixed expanded modes display issues

### PR DESCRIPTION
**Pull request by robyww**
- always does single mode when the is only one plot
  - better use of expanded mode toolbar space using flex layout
  - fixed: color change failing when mask is plotted

### CODE REVIEW

**Comment by ejoliet** [comment]
Thanks for looking at it!
I've checked that calling external viewer gives correctly single view mode on one image and tiled view on next images.
But when trying the expand mode on the 2x2 grid from here:
http://localhost:8080/firefly/demo/ffapi-highlevel-test.html

I can only see one image (single view?) and options to switch to tiled view or available list are no longer displayed. Could you check?

**Comment by robyww** [comment]
You are right.  The ffapi-highlevel-test.html has all the images in different groups. The options button should have been there to choose the images.  However, there is something still not right in how we are doing grouping, I am going to look at it a little more.

**Comment by robyww** [comment]
@ejoliet OK, i think i have fixed the bugs. You are welcome to look at it again or I can go ahead and merge.

**Comment by ejoliet** [comment]
Looks good. Review completed.

**Pull request merged**
