### PR TITLE
Firefly-973, Firefly-974: Fixed Multiple Issues

### PR DESCRIPTION
**Pull request by robyww**
#### [Firefly-973](https://jira.ipac.caltech.edu/browse/FIREFLY-973), [Firefly-974](https://jira.ipac.caltech.edu/browse/FIREFLY-974): Fixed Multiple issues
   - [Firefly-973](https://jira.ipac.caltech.edu/browse/FIREFLY-973) Fixed finder chart performance problem
       - updated the revisions of package.json libraries
       - optimized getLayouInfo() will not create a new object unless necessary
       - workers: when worker deleted it  will now fire a reject for all outstanding promises
       - better expired plot checking in RawDataOps
  - [Firefly-974](https://jira.ipac.caltech.edu/browse/FIREFLY-974): popout mouse readout not showing flux
  - _Bug fix_: FITS Information dialog was not showing file size
  - _Bug Fix_: Multi product viewer "All Images" option not showing the correct file when file changed by DataProductAnalyzer
  - _Bug Fix_: fixed non-passive event error warning coming from chrome
#### Testing
   - _finderchart:_ https://firefly-973-fc-performance.irsakudev.ipac.caltech.edu/applications/finderchart/
       - Load table of target, performance should be normal
       - Click on the info button for an image. You should see the file size.
   - _Sofia_: https://firefly-973-fc-performance.irsakudev.ipac.caltech.edu/applications/sofia
        - Flux information should show up on the popup mouse readout
        - It should not matter if you get at the first HDU from the pull down or form show "All Images"
   - _version_: 2022.1-DEV:HEAD_0497

### CODE REVIEW

**Comment by lrebull** [comment]
Some of it is better, but it's still struggling. See movie attached. (Sorry!)

https://user-images.githubusercontent.com/23038600/160191375-da524ae0-0fcd-40c4-bcd7-95732869eda0.mp4

**Comment by lrebull** [comment]
oh, i updated Firefox this morning (probably shouldn't have done that, mid-test cycle!) so now it's MacOS 10.14.6, Firefox 98.0.2.

**Comment by robyww** [comment]
I will work on it somemore

**Comment by lrebull** [comment]
FC still broken, just like friday, sorry...

https://user-images.githubusercontent.com/23038600/160490601-316d1548-30cb-4824-ab3d-266978e127dd.mp4

**Comment by lrebull** [comment]
the good news is that the sofia one is fixed, though....!

**Comment by lrebull** [comment]
WOO HOO WORKS ON ALL THREE BROWSERS

i still have to click “send to background” twice, but the list of input targets doens’t change column names, and importantly the image pane doesn’t crash. nice!!

**Comment by ejoliet** [comment]
@robyww you did it!

**Pull request merged**
