### PR TITLE
Firefly-738: Add parsing wise and 2mass type id entries

### PR DESCRIPTION
**Pull request by robyww**
Firefly-738: Add parsing wise and 2mass type id entries

  - Parsing entries such as 132405.64-552712.2  or J140320.67+542028.6
  - Clean up target panel algorithm code (originally ported from java)

_ticket_: https://jira.ipac.caltech.edu/browse/FIREFLY-738

_To Test:

 - https://fireflydev.ipac.caltech.edu/firefly-738-parsing-coords/firefly/
 - Try the id's from the ticket

### CODE REVIEW

**Comment by lrebull** [comment]
Nice!!!
for some reason, the SEIP targets (which were resolved by NED a few days ago) are not being resolved at all right now, so SSTSL2 J140258.51+542318.3 isn't working. Not sure if this is a transient problem that has been plaguing my testing of Radar in the last few hours.
I failed to explain fully the IRAS source names. Because the spatial resolution is so much worse for IRAS, 14013+5435 actually means 14h01.3m + 54d35m and you're resolving it as 14h01m03s which is probably fine, given the uncertainty in the IRAS positions, but i thought it was worth mentioning.
MSX names are parsed! and short GLIMPSE are, but long glimpse aren't, which seems weird. (G102.0360+59.7715 works, SSTGLMA G016.9536+00.7923 doesn't.) but this is probably also ok!!

**Review by ejoliet — APPROVED** [review]
Tested - seems to work as expected! 
Thanks!

**Comment by robyww** [comment]
> MSX names are parsed! and short GLIMPSE are, but long glimpse aren't, which seems weird. (G102.0360+59.7715 works, SSTGLMA G016.9536+00.7923 doesn't.) but this is probably also ok!!

@lrebull I implemented a parser to look at stuff like `G102.0360+59.7715` but `SSTGLMA G016.9536+00.7923` would need sent to a name to a name resolver (ned or simbad). Are you saying that this is the wrong thing to do?

**Comment by lrebull** [comment]
At the time I tried it, the name "SSTGLMA G016.9536+00.7923" wasn't resolved at all, nor was SSTSL2 J140258.51+542318.3. I am trying it now in your build, and neither one is resolved right now either. I don't know if something has gone down (at NED?) because the name "SSTSL2 J140258.51+542318.3" worked when I made this ticket and explicitly told me "resolved by NED."

**Comment by robyww** [comment]
yes, I have confirm that the is a problem getting this resolved with NED. It is working on the website but not from the API

**Comment by robyww** [comment]
> I failed to explain fully the IRAS source names. Because the spatial resolution is so much worse for IRAS, 14013+5435 actually means 14h01.3m + 54d35m and you're resolving it as 14h01m03s which is probably fine, given the uncertainty in the IRAS positions, but i thought it was worth mentioning.

OK, then I will keep it the way it is. This seems more consistent for the parser. It is matters later I can always change it.

**Pull request merged**
