### PR TITLE
DM-7789: add .babelrc and modified karma.conf.js

### PR DESCRIPTION
**Pull request by lznakano**
Updated the javascript unit testing environment:
 

-   add .babelrc
-  modified karma.conf.js in buildScripts
-  modified package.json to update karma libraries
- To run the javascript unit test

1. clone firefly_test_data repository
2. build firefly 
3. cd /hydra/cm/firefly/src/firefly

  npm run test-unit -s

I did not find a way to completely remove the karma.conf.js file in buildScripts directory. I only fond the way to make it shorter and eliminated all webpack related definition.

Please test it!

### CODE REVIEW

**Comment by loitly** [comment]
I've reviewed this pull request.  Here are my suggestions.
 
 - Don't use .babelrc to config babel for mocha.  babelrc is used by babel globally.  This may interfere with other processes, like webpack.  Instead, create a mocha-init.js file to initialize babel.
 - Remove all footprint of karma for now.  It's really confusing when I see changes to karma libraries and karma.conf.js config file, but yet we are not using it.  We can add it back in when we actually use it.  All of these libraries and config files would be gone.
    buildScript/karma.conf.js
    src/firefly/karma.conf.js

    "karma": "^1.3.0",
    "karma-chai": "^0.1.0",
    "karma-cli": "0.0.4",
    "karma-coverage": "^0.2.7",
    "karma-mocha": "^0.1.10",
    "karma-mocha-reporter": "^1.0.2",
    "karma-phantomjs-launcher": "^0.1.4",
    "karma-sinon-chai": "^0.3.0",
    "karma-webpack": "^1.8.0",

I can push my changes if you like.

**Comment by lznakano** [comment]
Yesterday after my struggles to merge the karma.conf.js to webpack.conf.js, I found that karma was not used at all. I called Emmanuel this morning to discuss if it is OK to remove karma.  He thought that we may still need to use it.  So I did not remove it.  I agree with you that it caused a lot of confusions at the moment.  I spent two days to understand how karma works and how it works with mocha and webpack.  Please move .babalrc file to src/firefly.  It works the same.  I should have put it there.   Please go ahead to push your changes.    Thanks!

**Comment by loitly** [comment]
Also, I noticed this just now:
```
  A test suite for expr/Expression.js
    ✓ valid expression (functions)
    ✓ valid expression (operators)
{ error: 'Unknown variable',
  details: 'I do not understand your expression 2*sin(x)+y/z.',
  where: 'I got as far as "2*sin(x)+y/" and then saw "z".',
  why: 'That variable is unknown or has no value.' }
    ✓ invalid expression

```

Shouldn't the error causes test to fail?  It did not.

**Comment by loitly** [comment]
@lznakano @ejoliet , I've pushed my changes.  Once you guys are okay with it, Lijun can merge.
Below is a summary of my changes:
  - add jsTest into gradle 'test' task
  - remove .babelrc, replace with mocha-init.js
  - remove karma.config.js files
  - remove unused libraries
```
    "clean-webpack-plugin": "^0.1.3"
    "coveralls": "^2.11.2"
    "esprima-fb": "^14001.1.0-dev-harmony-fb"
    "istanbul": "^0.3.13"
    "istanbul-instrumenter-loader": "^0.1.2"
    "karma": "^1.3.0"
    "karma-chai": "^0.1.0"
    "karma-cli": "1.0.1"
    "karma-coverage": "^1.1.1"
    "karma-mocha": "^1.2.0"
    "karma-mocha-reporter": "^2.2.0"
    "karma-phantomjs-launcher": "^1.0.2"
    "karma-sinon-chai": "^1.2.4"
    "karma-webpack": "^1.8.0"
    "request": "^2.65.0"
    "rewire": "^2.3.1"
    "rewire-webpack": "^1.0.0"
    "sinon": "^1.17.6"
    "sinon-chai": "^2.7.0"

```

**Comment by tgoldina** [comment]
Regarding 'invalid expression' test. The test succeeded because it was
testing invalid expression and expected to get back object with 'error'
field etc.

2016-10-04 16:10 GMT-07:00 loitly <notifications@github.com>:

**Comment by ejoliet** [comment]
Yes, the same way you would do it in java unit test with JUnit 4 like:

@Test (expected=IndexOutOfBoundsException.class)

**Pull request merged**
