### PR TITLE
Firefly-841: UI improvements

### PR DESCRIPTION
**Pull request by robyww**
Firefly-841: UI improvements

  - Expose more zoom buttons to the image embedded zoom menu
  - Enabled options to control and turn off the active tool on the image (distance, extract, area select)
  - Shift key will always allow for only scrolling

_ticket:_
https://jira.ipac.caltech.edu/browse/FIREFLY-879

_testing_
 - Firefly: https://fireflydev.ipac.caltech.edu/firefly-879-ui-improve/firefly/
 - ZTF: https://firefly-879-ui-improve.irsakudev.ipac.caltech.edu/applications/ztf/
 - FinderChart:  https://firefly-879-ui-improve.irsakudev.ipac.caltech.edu/applications/finderchart/

### CODE REVIEW

**Comment by lrebull** [comment]
Really cool!
suggestion for wording -- will need to be discussed, I think, but here are my votes:

- "finish extraction tool"
- "finish distance tool"
- "finish select tool"

**Comment by robyww** [comment]
It really needs to be shorter. There are cases where there is not much room.

**Comment by lrebull** [comment]
ok, can at least omit "tool" from each one, so it'd be (note last one is different)

- "finish extraction"
- "finish distance"
- "finish selection"

but i do think this should be discussed tomorrow with ccb-science

**Comment by ejoliet** [comment]
I really like the minimal change that gives now a full visibility and control of what is enabled and less click to disable the modes. Great suggestion and implementation.

**Pull request merged**
