### PR TITLE
Ff94 webdav bug

### PR DESCRIPTION
**Pull request by tgoldina**
Follow-up for FIREFLY-94: fixes for bugs discovered while testing LSST workspace.
https://jira.lsstcorp.org/browse/DM-13112

See SUIT pull request at https://github.com/lsst/suit/pull/15 for the info how to test.

### CODE REVIEW

**Comment by tgoldina** [comment]
In the two latest commits:

- fixed Bad Request, when saving a table to workspace. This was a missed case from firefly-53.

- added missed authorization credentials to a connection in IPACTableFromSource. This was causing 401 Unauthorized, when querying TAP schema from an LSST TAP server, which now requires authorization.

I've also added more error checking to IPACTableFromSource. Since URLDownload treats only the statuses between 300 and 400 as failures, any other bad status can go unnoticed. In my case, we happily parsed the returned html into an IPAC table with one column "<html>". After my change, IPACTableFromSource will treat HTTP status less than 200 or more or equal than 300 as a failure. This is consistent with HTTPServices. 
@loitly , @robyww, please let me know if you see a problem with this.

**Comment by loitly** [comment]
> HTTP status less than 200 or more or equal than 300 as a failure. This is consistent with HTTPServices

Technically, 3xx are not errors.  It may just require additional steps.  In HttpServices case, follow-redirect is turned on.  So, already some of the 3xx should be handled already.  In other cases, we may decide to say it's an error.  But in general, 3xx are not errors.

**Comment by tgoldina** [comment]
I don't know why URLDownload throws FailedRequestException on `responseCode>=300 && responseCode<400`, I did not want to change this behavior, in case something is relying on it. No changes there since 2017. So I just wanted to make sure we catch all other error statuses when getting table from URL.

**Comment by loitly** [comment]
@tgoldina what you did is correct.   I was only commenting on the 3xx status and how HttpServices are treating it.

**Pull request merged**
