### PR TITLE
Firefly-1291: obscore data products result should show search target

### PR DESCRIPTION
**Pull request by robyww**
#### Testing
- https://firefly-1291-search-target.irsakudev.ipac.caltech.edu/irsaviewer/dce
- do a DCE search, the overlay position should be the search target

### CODE REVIEW

**Comment by lrebull** [comment]
I'm running into this bug while testing https://jira.ipac.caltech.edu/browse/FIREFLY-1196

**Comment by lrebull** [comment]
(i think, anyway. still testing)

**Comment by lrebull** [comment]
If I start a clean session and only ask for one target over many data sets, it works great. I run into trouble if I search on more than one different target.

**Comment by wmiipac** [comment]
I did position searches for few object with AKARI, so there are  few tabs in the table panel.  when navigating through the tabs, target is overlayed on images correctly.  I closed few  table tabs, the target positions are still on the coverage map. Not sure if this is desired, may be confusing to the user.

**Comment by robyww** [comment]
@wmiipac that is the way it has always worked. I don't know if it is desired or not but it is outside the scope of this ticket. If it is a problem we can work on it for another ticket.

**Comment by robyww** [comment]
@lrebull I searched more than one target and it seemed to work for me. I will need more details if there is an issue.

**Review by wmiipac — APPROVED** [review]
Works as expected. Thanks for a quick fix!

**Comment by lrebull** [comment]
Huh. i went to make a movie, and naturally I couldn't make it fail. I don't know what was going on before.

**Pull request merged**
