### PR TITLE
Firefly: multiple tickets:  Firefly-678,  Firefly-380,  Firefly-727, Firefly-731

### PR DESCRIPTION
**Pull request by robyww**
### Implements multiple tickets

 - Firefly-678: coverage now supports HMS coordinate strings in the table
 - Firefly-380: coverage now updates when a table is filtered to empty
 - Firefly-727: coverage now updates correctly when a empty table is loaded
 - Firefly-731: keyboard shortcuts now supported when adding extensions from python/remote API
 - Firefly-735: reverse the scroll wheel zoom dir
 - Firefly-720: fixed: document scroll with mouse wheel zoom
 - Firefly-736: only a partial fix to work around safari bugs, we might work on it more later
 - `dispatchRecenter` now supports `updateFixedTarget` parameter
 - Cleaned up CoordUtil.js - removed options we don't and will probably never use
 - Added KOA to TAP list

#### Tickets:
 - https://jira.ipac.caltech.edu/browse/FIREFLY-678
 - https://jira.ipac.caltech.edu/browse/FIREFLY-380
 - https://jira.ipac.caltech.edu/browse/FIREFLY-727
 - https://jira.ipac.caltech.edu/browse/FIREFLY-731
 - https://jira.ipac.caltech.edu/browse/FIREFLY-720
 - https://jira.ipac.caltech.edu/browse/FIREFLY-735
 - https://jira.ipac.caltech.edu/browse/FIREFLY-736

#### To test:

https://fireflydev.ipac.caltech.edu/firefly-multi-ticket/firefly/

  - try searching KOA
  
 For coverage:
   -  do a search with results, the following it up with a search with no results )
      - I did tap `koa` - `koa_hires` - `kepler10` - `100 arcsec`, followed by the coords `1,2`
   - filter a table so it is empty
   - read in a table with hms coordinates (example in Firefly-727)
   
The python extension shortcut is hard to test since we have to release the `firefly_client` that accesses the features
 
the `dispatchRecenter` can be tested by @cwang2016 
```js
firefly.action.dispatchRecenter({
                        plotId:pId,
                        centerPt:pos[nextIdx],
                        updateFixedTarget:true
                    });
```

### CODE REVIEW

**Review by ejoliet — COMMENTED** [review]
I started to test and bringing result form one single search individually is ok (KOA, then separately the HMS test) but when i added a table search and went back to the other table, it went white. And try-view is no longer working, had to reload the page.
I'm using Safari.

I noticed that the Gator search doesn't really come back so i'm not usre if it's not related to the deployed version running out of memory or dev in IRSA?

**Comment by robyww** [comment]
Hmmm. I will look at it.

**Comment by cwang2016** [comment]
I did try dispatchRecenter into a sample that shows several targets in sequence on the same HiPS and MOC layers, the image center is updated as expected when the target changes. Thanks.

**Review by cwang2016 — APPROVED** [review]

**Review by ejoliet — APPROVED** [review]
Tested quickly every ticket - looks fine.
Thanks for fixing all those in one PR.

**Pull request merged**
