### PR TITLE
Firefly-849,842,845,IRSA-4224: Multiple bugs fixed

### PR DESCRIPTION
**Pull request by robyww**
#### Multiple bugs fixed

  - IRSA-4224: UI covering recenter after UI changes
  - Firefly-849: magnified image vanish
  - Firefly-842: SOFIA images not centered on screen
  - Firefly-845: Datalink fail when image url string has a plus (+) sign

#### Tickets:

  - https://jira.ipac.caltech.edu/browse/FIREFLY-841
  - https://jira.ipac.caltech.edu/browse/FIREFLY-849
  - https://jira.ipac.caltech.edu/browse/FIREFLY-845
  - https://jira.ipac.caltech.edu/browse/IRSA-4224

#### Testing:

 - _firefly_: https://fireflydev.ipac.caltech.edu/mutiple-bugs-849-842-845-i4224/firefly/
 - _sofia_: https://mutiple-bugs-849-842-845-i4224.irsakudev.ipac.caltech.edu/applications/sofia/
 - See tickets for bugs

### CODE REVIEW

**Comment by robyww** [comment]
IRSA-4224 also appears to be working for me. Are you sure you are testing against the firefly build listed above?

**Comment by lrebull** [comment]
I'll try a "new private window" .. i thought we fixed the issue where nearly every bug I find is due to stale cookies...

**Comment by robyww** [comment]
OK - I see the problem with firefly-845, it is not changing the stretch it is changing plots to a non-selected one when you click off. I will fix that.  I guess you are going to have to demonstrate IRSA-4224  not working. To me it appears to be fixed.

**Comment by robyww** [comment]
IRSA-4224 was broken into two tickets. #1 was related to the UI changes. That is what I am fixing here. 

> the center plot/recenter button is either mostly buried or entirely buried

The #2 and #3 you moved (at my request) to IRSA-4231. They are pre-existing issues. I have not even seriously studied these two so I can't comment on them yet. Right now I am trying to fix stuff related to the UI changes.

All the UI change tickets have a master ticket of https://jira.ipac.caltech.edu/browse/FIREFLY-841.

**Comment by robyww** [comment]
> I'm unclear on how I should test this. I am not getting an error when uploading what I think I'm supposed to be uploading, so maybe it is fixed?

Firefly-845 is fixed it the tables load. Before there was an error in the DataProductViewer area.

**Comment by lrebull** [comment]
FIREFLY-842 is also fixed.
I am not sure about Firefly-845, because I am not sure how to test it. I thought it was working, but then Emmanuel was getting a different error message.

**Pull request merged**
