### PR TITLE
Irsa 6482 sofia UI fixes by feedback

### PR DESCRIPTION
**Pull request by wmiipac**
View [related ticket](https://jira.ipac.caltech.edu/browse/IRSA-6482) for details. 
Add a help anchor in propertysheet, requested in SOFIA test report. this change will affect all IRSA apps.
Test:
https://irsa-6482.irsakudev.ipac.caltech.edu/applications/sofia/

do a position search and go to Details tab, try help anchor.

### CODE REVIEW

**Comment by lrebull** [comment]
(also copied into jira ticket)

103 - done. still somewhat blinky/fussy but improved.

105 - done!

106 - done!

110 - I'm .. not sure! Movie:

https://github.com/user-attachments/assets/c4e419b4-49f1-4b3e-95eb-d850caa66e02

**Comment by wmiipac** [comment]
110 - I'm .. not sure! Movie:

should be fix in this build, please test again. thanks!
https://irsa-6482-sofia.irsakudev.ipac.caltech.edu/applications/sofia/

**Comment by lrebull** [comment]
ok, so it will go properly to the details-specific help anchor even when in any other tool? cool!!

**Comment by wmiipac** [comment]
yes, this should work in all IRSA apps.

**Pull request merged**
