### PR TITLE
UI changes

### PR DESCRIPTION
**Pull request by robyww**
#### UI changes 

 - Us less space in the header bar area
 - Compress and move the image tool bar to the image area
 - Make the mouse readout have two modes
     - A small one under the images
     - A popup larger one
 - Make the thumbnail and magnifier larger and place in the popup mouse readout
 - Remove some borders around the components
 - Make new image toolbar line up similar to other visualizer toolbars

_ticket:_ https://jira.ipac.caltech.edu/browse/FIREFLY-832

#### Testing

- Firefly: https://fireflydev.ipac.caltech.edu/firefly-832-ui-changes/firefly/
- Slate: https://fireflydev.ipac.caltech.edu/firefly-832-ui-changes/firefly/slate.html
- IrsaViewer: https://firefly-832-ui-changes.irsakudev.ipac.caltech.edu/irsaviewer/
- Time Series - https://firefly-832-ui-changes.irsakudev.ipac.caltech.edu/irsaviewer/timeseries
- FinderChart: https://firefly-832-ui-changes.irsakudev.ipac.caltech.edu/applications/finderchart/
- Sofia: https://firefly-832-ui-changes.irsakudev.ipac.caltech.edu/applications/sofia/
- Gator or Atlas: https://firefly-832-ui-changes.irsakudev.ipac.caltech.edu/

### CODE REVIEW

**Comment by loitly** [comment]
Readout-Popup:
- magnifier for `Lock by click` is buggy.  sometimes shows blank with error in console when clicking around.
`Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null`
Triview slider:
- now that the borders are removed, we can make the  gap narrower.  save space and nicer looking

Personal Preferences:
- Images tab:  triview with more than 10 images showing.
  - would be nice to have the blue 'x' at top right corner also show/hide like the zoom icons.  It's a bit busy when you have so many of them in that small area.
  - i think the thick blue border boxes for inactive images are a bit too distracting.  maybe just me, because it has been this way forever.
- Image Toolbar:
  - is the blue bar separator needed anymore?  looking to the right at chart, it also has just 'space' separator and it looks fine.

Overall, it looks great.  Definitely an improvement.

**Comment by robyww** [comment]
@loitly I can't see to duplicate the bug you saw. 

I did do the following:

- narrowed the gap in the resizer
- show the delete x for only the image with the mouse
- I think your right about the inactive image border- I changed it to be `rgba(0,0,0,.1)`
- I think the separators should stay for now. I have felt for a long time that the chart toolbar space separator just looks like a bug and not purposeful. We might want to consider changing the chart. I did make the separators a little shorter in the toolbar and I am open the making them a little more lower key.

**Comment by lrebull** [comment]
(1) I do see the same thing Loi does with the magnifier and click to lock.

(2) my text from Slack just so that it's kept linked to this ticket:  https://caltech-ipac.slack.com/archives/CG82RK4EM/p1630343936037000

(3) I see what Loi means about having the blue "delete this image" x go away like the magnifying glass. But, related to this - if you load some multi-HDU images (like from Herschel) as part of your search, there is some strangeness associated with the extra screen real estate dedicated to scrolling through the panes. I am not sure there is a good solution to this -- it's basically like this on ops too. (And I'm sure that I can dig back up some of the tickets on this that I created last time this came up.) It's also bound up in what happens when you click to select a region, and you get a new menu with choices. Though, interestingly, said menu doesn't show up in the multi-plane Herschel images. See attached screenshot.
Screen Shot 2021-08-30 at 3 11 47 PM

**Comment by robyww** [comment]
@loitly @lrebull can you give me a little more detail about how you make this click-lock/magnifier bug happen?

**Comment by lrebull** [comment]
LOL i started to make a movie but discovered new and interesting bugs in the build you just made! i can't show you how i triggered the other bug, for reasons that will become apparent in the video...

https://user-images.githubusercontent.com/23038600/131413421-9c5c2930-81f6-4fcb-8e2d-c87a77b5d8b2.mp4

**Comment by loitly** [comment]
> @loitly @lrebull can you give me a little more detail about how you make this click-lock/magnifier bug happen?

On an image, click `expand readout` -> `Lock by click`.  Then, click around the image while you have your console open.  You will see the TypeError at the same time when the magnifier goes blank.

**Comment by ejoliet** [comment]
Luisa, I think because your active image is empty because not covered, select existing correct one should work?
--
Emmanuel Joliet
NASA/IPAC  Infrared Science Archive
MS 100-22, Caltech, Pasadena, CA 91125
Office: 170
Email:  ***@***.***
Phone:  (626) 395-1489

On Aug 30, 2021, at 15:24, Loi Ly ***@***.***> wrote:

﻿

@loitly<https://github.com/loitly> @lrebull<https://github.com/lrebull> can you give me a little more detail about how you make this click-lock/magnifier bug happen?

On an image, click expand readout -> Lock by click. Then, click around the image while you have your console open. You will see the TypeError at the same time when the magnifier goes blank.

**Comment by lrebull** [comment]
Ah, yes, you're right about the catalog failure. But the pop-up window for the list of images and the pop-up for the magnifier still vanish for me instantly as in the video.

**Comment by robyww** [comment]
Pushed a commit a couple of hours ago. I issues so far have been resolved.

**Comment by robyww** [comment]
@lrebull 

> But, related to this - if you load some multi-HDU images (like from Herschel) as part of your search, there is some strangeness associated with the extra screen real estate dedicated to scrolling through the panes. I am not sure there is a good solution to this -- it's basically like this on ops too. (And I'm sure that I can dig back up some of the tickets on this that I created last time this came up.) It's also bound up in what happens when you click to select a region, and you get a new menu with choices. Though, interestingly, said menu doesn't show up in the multi-plane Herschel images. See attached screenshot.

1. In the case of your image above the rest of the context toolbar is cut off because the image area is too small. I don't have any good solution for an alternative
2. For the multi HDU images (what your arrows are point at): It appears indented because in some cases, when a HDU has a name, more space is required. Therefore there is a fixed amount of space for the label section. Otherwise if we did not do that the whole toolbar would bounce around as the user arrows through the HDUs.

**Comment by lrebull** [comment]
hi - in regards to the shifting down of the images -- we talked past each other on this before too. I can show you "in person" next time we're on the same call, maybe one of the CCBs.

**Comment by ejoliet** [comment]
@robyww Do you have a TimeSeries version of it?

**Comment by ejoliet** [comment]
NVM, i guess is the Gator case... let me try.

**Comment by robyww** [comment]
https://firefly-832-ui-changes.irsakudev.ipac.caltech.edu/irsaviewer/timeseries

**Comment by wmiipac** [comment]
I tested the irsaviewer in IRSA sw based applications:
**Catalog (Gator) search**: the image tool bar is miss the image align lock icon, not sure if this is by design, even with added coverage images the image alignment icon didn't show up. see attached screenshot 
Screen Shot 2021-09-02 at 5 28 02 PM

**Atlas search**: test case: Spitzer SEIP image search, 
test case: Spitzer SEIP image search, 
https://firefly-832-ui-changes.irsakudev.ipac.caltech.edu/data/SPITZER/Enhanced/SEIP/
from search result page, launch external image viewer via irsaviewer, the list popup does not work, see attached screenshot
Screen Shot 2021-09-03 at 8 55 38 AM

**Radar:** test case with HD 858 search, retrieve	SED data from VizieR for plot, and overlay search region on coverage. everything works as expected.
Screen Shot 2021-09-02 at 4 46 55 PM

**Comment by robyww** [comment]
There are two issues that you brought up.
 > Catalog (Gator) search: the image tool bar is miss the image align lock icon, not sure if this is by design, even with added coverage images the image alignment icon didn't show up. see attached screenshot

This is by design and has always worked like this. Gator does the following config.
```js
     firefly= {
            options: {
                MenuItemKeys: {matchLockDropDown:false, lockImage:false}
            }
        };
```

> from search result page, launch external image viewer via irsaviewer, the list popup does not work, see attached screenshot


This is because of the `BigInt` issue. This is actually already fixed bug the overall fix will be when @loitly merges https://github.com/Caltech-IPAC/firefly/pull/1125.

**Pull request merged**
