### PR TITLE
Firelfy-1490: TAP catalogs can now be locked to a schema

### PR DESCRIPTION
**Pull request by robyww**
#### Testing
- https://firefly-1490-lock-tap-schema.irsakudev.ipac.caltech.edu/applications/euclid/
- bring up euclid choose the sidebar option for Euclid catalogs
   - it will show only wise catalogs but can be changed to euclid in the future when we have some

### CODE REVIEW

**Review by kpuriIpac — APPROVED** [review]
Looks good to me. Tested euclid catalogs and it works. 

a couple of questions: 
1. How would this eventually relate to the description of `#10 `in the [Euclid Doc](https://docs.google.com/spreadsheets/d/1SH6sOB6mI8O3y1IBtbhQRp0ar8CamhK__5X0nvZJV6s/edit?pli=1&gid=0#gid=0) ? :
  `Columns selection in "Inspect Sources" search screen`.
2. This is a general comment, unrelated to your PR, but I found this bug by playing around in the test build:
   -  Load up euclid. Do a search with Euclid Catalogs or TAP (any search except `Inspect Sources` or `Explore Regions`). This takes you to the `results` or euclid home page, but it's empty. You only see your results in the `/euclid/viewer-region` or` /euclid/viewer-source` path when you do a `Explore Regions` or `Inspect Sources` search. I'll create / add this to an existing ticket?

**Comment by robyww** [comment]
> How would this eventually relate to the description of #10 in

This is a catalog. The tap search screen will be locked to a set of euclid catalogs and then the user can control (using the stand TAP catalog selection) which columns he wants. That is what the check boxes on the columns selection on tie right side of the TAP screen are fo.

**Comment by robyww** [comment]
> This is a general comment, unrelated to your PR, but I found this bug by playing around in the test build:
Load up euclid. Do a search with Euclid Catalogs or TAP (any search except Inspect Sources or Explore Regions). This takes you to the results or euclid home page, but it's empty. You only see your results in the /euclid/viewer-region or /euclid/viewer-source path when you do an Explore Regions or Inspect Sources search. I'll create / add this to an existing ticket?

This is out of scope for this ticket. It should be fix when we redo the results area. I am not sure if that is what you are working on now. This ticket is just about locking the catalogs to a Euclid TAP schema.

If you are working oh then then you probably want to rebase after the merge.

**Comment by kpuriIpac** [comment]
> > How would this eventually relate to the description of #10 in
> 
> This is a catalog. The tap search screen will be locked to a set of euclid catalogs and then the user can control (using the stand TAP catalog selection) which columns he wants. That is what the check boxes on the columns selection on tie right side of the TAP screen are fo.

Yes that part I understand, same as TAP. But my bad, I should have been more specific. I just meant to ask how it related to `Inspect Sources search screen` from the comment in the doc, since this is a tap search screen instead (locked to a set euclid catalogs).

**Comment by kpuriIpac** [comment]
> > This is a general comment, unrelated to your PR, but I found this bug by playing around in the test build:
> > Load up euclid. Do a search with Euclid Catalogs or TAP (any search except Inspect Sources or Explore Regions). This takes you to the results or euclid home page, but it's empty. You only see your results in the /euclid/viewer-region or /euclid/viewer-source path when you do an Explore Regions or Inspect Sources search. I'll create / add this to an existing ticket?
> 
> This is out of scope for this ticket. It should be fix when we redo the results area. I am not sure if that is what you are working on now. This ticket is just about locking the catalogs to a Euclid TAP schema.
> 
> If you are working oh then then you probably want to rebase after the merge.

Yes I agree, it's out of scope for this ticket, I wanted to mention it here as I discovered it by doing a search directly from the tap screen, before having done a `Inspect Sources/Explore Regions` search, just to document that's how I found this bug. I am not working on this now, but I'll work on it as part of the results area ticket.

**Pull request merged**
