### PR TITLE
Irsa 3557 adding unwise dataset

### PR DESCRIPTION
**Pull request by ejoliet**
This is a tiny change in config file in order to add WISE unWISE dataset to image search.
https://jira.ipac.caltech.edu/browse/IRSA-3557

Test version here:
https://irsa-3557.irsakudev.ipac.caltech.edu/irsaviewer/

### CODE REVIEW

**Comment by ejoliet** [comment]
Reviewer feedback included. this can be merged.

**Comment by lrebull** [comment]
I still see W3W4 ..?

**Comment by ejoliet** [comment]
Yes, didn’t redeploy but config file Is ok. I will merge if there aren’t other problems found.

**Comment by lrebull** [comment]
Yes, it all looks ok to me.

**Pull request merged**
