### PR TITLE
Firefly-1263: optimize fits table read

### PR DESCRIPTION
**Pull request by robyww**
#### [Firefly-1263](https://jira.ipac.caltech.edu/browse/FIREFLY-1263): optimize fits table read

   - Make some simple changes to optimize read very large fits table.

#### Testing

  - https://fireflydev.ipac.caltech.edu/firefly-1263-optimize-fits-table-read/firefly
  - read a large fits table

### CODE REVIEW

**Comment by kpuriIpac** [comment]
The code change looks good (should've thought of this!). But on the test build, I get the following error trying to load the big table (from the big 3.5 GB fits file that Gregory linked to: 71 cols x 8633452 rows): 

```
Table Load Error:
Error fetching https://fireflydev.ipac.caltech.edu/firefly-1263-optimize-fits-table-read/firefly/CmdSrv/sync?cmd=tableSearch: code: 502, text:
```

Perhaps the test build needs to have a higher memory limit? (4Gi or 8Gi). 

Trying to test it locally and it doesn't crash, but is stuck in seemingly an endless loop of trying to load, will add breakpoints and try to make it work, and I can report back on what I find. (seems like it runs through all the rows as expected, but doesn't render the table after that for some reason - this might be something on my end)..

**Comment by robyww** [comment]
I think it is memory, but we could give better errors. I was able to load it with a large server (16 GB)

**Comment by kpuriIpac** [comment]
> I think it is memory, but we could give better errors. I was able to load it with a large server (16 GB)

Yes a better error message would help. It appears my local Tomcat is also set to max memory of 16 GB, but this file still doesn't load for me (no error though, so I'm still poking to try and find out why it wouldn't load - it creates the entire **DataGroup** correctly and returns the **result** as well)

**Comment by robyww** [comment]
We can pursuit a better message in a later PR. This work is really just about optimizing the FITS reading part.

**Pull request merged**
