### PR TITLE
Firelfy-1551: hpx feedback

### PR DESCRIPTION
**Pull request by robyww**
#### [Firefly-1551](https://jira.ipac.caltech.edu/browse/FIREFLY-1551)

  - default to healpix grid
  - add option the set grid size large/small
  - heatmap mode

#### Testing
- https://fireflydev.ipac.caltech.edu/firefly-1551-hpx/firefly/

### CODE REVIEW

**Comment by lrebull** [comment]
It does seem to work -- note to the others, try 'new private window' to have it not remember what mode you were in before the last time you used it.

I do not seem to have 'heatmap' as a mode anywhere. where should i be looking? see screenshot.
Screenshot 2024-09-05 at 3 21 54 PM

**Comment by robyww** [comment]
@lrebull Sorry I messed up a pushed. I is rebuilt now. You will see the heatmap option.

**Comment by lrebull** [comment]
I can't get the coverage map to load at all, in a regular or 'new private window'. here i sits for longer than the timescale of my ADHD :
Screenshot 2024-09-06 at 9 19 38 AM

**Comment by robyww** [comment]
@lrebull I left a comment on slack as well... try again

**Comment by lrebull** [comment]
Ok, i see heatmap now! i think i like it, but as for the other stuff, the other people who had more strong feelings should check it.
when i leave it in 'heatmap', and go add another catalog, it reverts to the default setting for all catalogs (new and old).
the dashed lines for the ellipse are a nice addition; makes it more clear that they're not the same as individual sources.

**Comment by robyww** [comment]
> when i leave it in 'heatmap', and go add another catalog, it reverts to the default setting for all catalogs (new and old).

Yes, I am not sure what to do about this. I did not want to to ever default to heatmap since it is opaque.

**Pull request merged**
