### PR TITLE
Firefly-907: provide a way to disable extraction

### PR DESCRIPTION
**Pull request by robyww**
#### Firefly-907: provide a way to disable extraction

 - also fixes Firelfy-934, a font size bug
 - also fixes: firefly-431

#### Tickets
- [FIREFLY-907](https://jira.ipac.caltech.edu/browse/FIREFLY-907)
-  [FIREFLY-934](https://jira.ipac.caltech.edu/browse/FIREFLY-934)
-  [FIREFLY-431](https://jira.ipac.caltech.edu/browse/FIREFLY-431)

#### Testing - this tests show the coverage can be disabled for Gator
- Version: 2022.1-DEV:firefly-907-extract-disable_c854
- https://fireflydev.ipac.caltech.edu/firefly-907-extract-disable/firefly/test/tests-main.html?test=IRSA+Gator+Table
   - click on toolbar of coverage, there should be no extract option
- https://fireflydev.ipac.caltech.edu/firefly-907-extract-disable/firefly/
   - extract will show in coverage

### CODE REVIEW

**Comment by lrebull** [comment]
I'm sorry; I'm super confused. again. video attached.

https://user-images.githubusercontent.com/23038600/152894526-0877010f-a1f8-4591-965c-6cc709da8801.mp4

**Comment by robyww** [comment]
@lrebull I should have given more details. You were on the right track, but the search resulted in a HiPS coverage so extraction will not show. Try `wise`/`m1`/`100 arcsec`, it will give a coverage with a FITS, then extract will show.

**Comment by lrebull** [comment]
Ah! of course, sorry, that makes sense. Of course, everything is down right now. I will try again later.

**Comment by lrebull** [comment]
I forgot to try yesterday when everything came back up, and today I can't get it to work at all. This is what I see when I try to do a catalog query, even in a new private window
Screen Shot 2022-02-09 at 9 45 36 AM
.

**Comment by lrebull** [comment]
Ok, yes, got it to work properly. I verify this works!

**Pull request merged**
